package simrunner;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.nio.file.*;
import java.util.*;
import java.util.List;
import simcore.MiniJson;
import simcore.RobotConfigXml;

/** Instructions, focused controls and resumable setup over the existing model workflow. */
public final class GuidedSetupWizard {
    private final JFrame window=new JFrame("FTC Forge — guided setup");
    private final GuidedSetupController controller;
    private final JPanel content=new JPanel(new BorderLayout(12,12));
    private final DefaultListModel<String> navigation=new DefaultListModel<>();
    private final JList<String> sidebar=new JList<>(navigation);
    private final JLabel status=new JLabel("Choose what you want to prepare.");
    private final JTextArea instructions=new JTextArea();
    private final JButton back=new JButton("Back"),next=new JButton("Next"),close=new JButton("Save and close");
    private GuidedSetupSession.Step step=new GuidedSetupSession.Step("","start");
    private GuidedParameterPanel parameters;
    private Map<String,Object> profile,scene;
    private boolean busy,rendering,savingLayout;
    private long generation;
    private final Map<Component,Boolean> enabledStates=new IdentityHashMap<>();
    private String diagnostics="";
    private final javax.swing.Timer debounce=new javax.swing.Timer(900,e->compileChanges());
    private Runnable leave=()->{};
    @FunctionalInterface private interface Task {Object run() throws Exception;}

    public static void main(String[] args) throws Exception {
        Path library=Path.of(args.length>0?args[0]:".local/models").toAbsolutePath();Path project=args.length>1&&!args[1].equals("-")?Path.of(args[1]).toAbsolutePath():null;
        var controller=new GuidedSetupController(library,project);
        if(args.length>2)controller.resume(Path.of(args[2]));
        SwingUtilities.invokeLater(()->new GuidedSetupWizard(controller).show());
    }
    private GuidedSetupWizard(GuidedSetupController controller){this.controller=controller;debounce.setRepeats(false);}
    private void show(){
        window.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);window.setMinimumSize(new Dimension(1000,740));window.setSize(1260,880);
        sidebar.setFixedCellWidth(255);sidebar.setBorder(BorderFactory.createEmptyBorder(12,8,12,8));window.add(new JScrollPane(sidebar),BorderLayout.WEST);
        content.setBorder(BorderFactory.createEmptyBorder(18,18,12,18));window.add(content);
        var footer=new JPanel(new BorderLayout());var buttons=new JPanel(new FlowLayout(FlowLayout.RIGHT));buttons.add(back);buttons.add(next);buttons.add(close);JButton details=new JButton("Technical details");buttons.add(details);footer.add(status);footer.add(buttons,BorderLayout.SOUTH);footer.setBorder(BorderFactory.createEmptyBorder(8,15,8,15));window.add(footer,BorderLayout.SOUTH);
        sidebar.addListSelectionListener(e->{if(e.getValueIsAdjusting()||rendering||busy)return;int target=sidebar.getSelectedIndex();if(target<0)return;var steps=controller.session.steps();if(target>=steps.size())return;boolean permitted=true;for(int i=0;i<target;i++)if(!controller.session.complete(steps.get(i))){permitted=false;break;}if(permitted||target<=steps.indexOf(step)){try{flushForNavigation();navigate(steps.get(target));}catch(Exception ex){failure(ex);refreshNavigation();}}else {status.setText("Complete the earlier step first; its instructions explain what is missing.");refreshNavigation();}});
        back.addActionListener(e->{if(!busy){try{flushForNavigation();var steps=controller.session.steps();int i=steps.indexOf(step);if(i>0)navigate(steps.get(i-1));}catch(Exception ex){failure(ex);}}});
        next.addActionListener(e->advance());close.addActionListener(e->saveClose());details.addActionListener(e->{String report=diagnostics.isBlank()?"No technical errors recorded.\nSession: "+controller.session.file:diagnostics;try{if(controller.lastLog!=null&&Files.exists(controller.lastLog))report+="\n\n"+Files.readString(controller.lastLog);}catch(Exception ignored){}var text=new JTextArea(report,20,85);text.setEditable(false);JOptionPane.showMessageDialog(window,new JScrollPane(text),"Technical details",JOptionPane.INFORMATION_MESSAGE);});
        window.addWindowListener(new WindowAdapter(){@Override public void windowClosing(WindowEvent e){saveClose();}});
        navigate(controller.session.goal().isEmpty()?step:controller.session.firstIncomplete());window.setLocationRelativeTo(null);window.setVisible(true);
    }
    private void header(String title,String text){
        var panel=new JPanel(new BorderLayout(0,10));var label=new JLabel(title);label.setFont(label.getFont().deriveFont(Font.BOLD,23f));panel.add(label,BorderLayout.NORTH);
        instructions.setText(text);instructions.setEditable(false);instructions.setOpaque(false);instructions.setLineWrap(true);instructions.setWrapStyleWord(true);instructions.setRows(4);instructions.setFont(label.getFont().deriveFont(14f));panel.add(instructions);content.add(panel,BorderLayout.NORTH);
    }
    private JPanel column(){var p=new JPanel();p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));return p;}
    private JPanel row(){return new JPanel(new GridLayout(0,2,8,6)){@Override public Dimension getMaximumSize(){return new Dimension(Integer.MAX_VALUE,getPreferredSize().height);}};}
    private void button(JPanel panel,String label,Runnable action){var b=new JButton(label);b.addActionListener(e->{if(!busy)action.run();});panel.add(b);}
    private void navigate(GuidedSetupSession.Step target){
        try{debounce.stop();step=target;controller.session.current(step);generation++;parameters=null;profile=null;scene=null;leave=()->{};content.removeAll();status.setText(step.page().equals("finish")?"Export or connect your setup, then choose Finish.":"Review this step, then choose Next.");
            switch(step.page()){case "start"->startPage();case "source"->sourcePage();case "scale"->scalePage();case "parts"->partsPage();case "physics"->physicsPage();case "motion"->motionPage();case "review"->reviewPage();case "scene"->scenePage();default->finishPage();}
            refreshNavigation();window.revalidate();window.repaint();
        }catch(Exception e){failure(e);header("This step needs attention","Your draft has been retained. Use Back to change the model selection, or correct its settings and resume this step.");var p=row();button(p,"Reload this step",()->navigate(step));button(p,"Advanced settings",this::advanced);content.add(p);window.revalidate();}
    }
    private void refreshNavigation(){
        rendering=true;navigation.clear();var steps=controller.session.steps();for(var s:steps)navigation.addElement((controller.session.complete(s)?"✓ ":"○ ")+s.label());sidebar.setSelectedIndex(steps.indexOf(step));back.setEnabled(!busy&&steps.indexOf(step)>0);next.setEnabled(!busy);next.setText(step.page().equals("finish")?"Finish":"Next");rendering=false;
    }
    private void work(String stage,Task task,Runnable done){
        if(busy)return;debounce.stop();busy=true;setControls(content,false);back.setEnabled(false);next.setEnabled(false);close.setEnabled(false);sidebar.setEnabled(false);status.setText(stage);long expected=generation;
        new SwingWorker<Object,Void>(){
            protected Object doInBackground()throws Exception{return task.run();}
            protected void done(){busy=false;setControls(content,true);close.setEnabled(true);sidebar.setEnabled(true);if(expected!=generation)return;try{get();done.run();}catch(Exception e){failure(e.getCause()==null?e:e.getCause());}refreshNavigation();}
        }.execute();
    }
    private static void visitControls(Component component,java.util.function.Consumer<Component> action){action.accept(component);if(component instanceof Container c)for(var child:c.getComponents())visitControls(child,action);}
    private void setControls(Component component,boolean enabled){setControls(component,enabled,enabledStates);}
    static void setControls(Component component,boolean enabled,Map<Component,Boolean> states){
        // Capture every state before parent controls propagate disabling to their editors.
        if(!enabled){visitControls(component,c->states.put(c,c.isEnabled()));visitControls(component,c->c.setEnabled(false));}
        else visitControls(component,c->{c.setEnabled(states.getOrDefault(c,true));states.remove(c);});
    }
    private void failure(Throwable error){diagnostics=error.toString();status.setText("Needs attention — "+friendly(error));var message=new JTextArea(friendly(error),5,72);message.setLineWrap(true);message.setWrapStyleWord(true);message.setEditable(false);JOptionPane.showMessageDialog(window,new JScrollPane(message),"Setup needs attention",JOptionPane.ERROR_MESSAGE);}
    private static String friendly(Throwable e){String text=e.getMessage()==null?e.toString():e.getMessage();if(text.contains("Traceback")){String[] lines=text.strip().split("\\n");text=lines[lines.length-1].replaceFirst("^[A-Za-z.]+Error: ","");}if(text.contains("Missing STL"))text+=". Select a ZIP containing the URDF and all its referenced STL files.";return text.length()>700?text.substring(0,700)+"… See Technical details.":text;}
    private Path choose(String title,boolean save,boolean directory){
        var c=new JFileChooser();c.setDialogTitle(title);if(directory)c.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        var accessory=new JPanel(new BorderLayout(4,8));var input=new JTextField(24);input.getAccessibleContext().setAccessibleName("Optional absolute path");accessory.add(new JLabel("Paste a file or folder path (optional):"),BorderLayout.NORTH);accessory.add(input);var use=new JButton("Select this path");accessory.add(use,BorderLayout.SOUTH);c.setAccessory(accessory);
        Runnable select=()->{try{Path path=Path.of(input.getText().strip()).toAbsolutePath();if(input.getText().isBlank()||(directory?!Files.isDirectory(path):!save&&!Files.isRegularFile(path)))throw new IllegalArgumentException(directory?"Enter an existing folder path.":"Enter an existing file path.");c.setSelectedFile(path.toFile());c.approveSelection();}catch(Exception e){JOptionPane.showMessageDialog(c,e.getMessage(),"Check the path",JOptionPane.ERROR_MESSAGE);}};use.addActionListener(e->select.run());input.addActionListener(e->select.run());
        return (save?c.showSaveDialog(window):c.showOpenDialog(window))==JFileChooser.APPROVE_OPTION?c.getSelectedFile().toPath().toAbsolutePath():null;
    }
    private void project(){Path path=choose("Choose team project folder containing sim.config",false,true);if(path!=null)try{if(!Files.isRegularFile(path.resolve("sim.config")))throw new IllegalArgumentException("This folder has no sim.config. Select the team project's simulator folder.");controller.session.data.put("project",path.toRealPath().toString());controller.session.data.remove("project_check");controller.session.save();navigate(step);}catch(Exception e){failure(e);}}
    private void startPage(){
        header("Let's set up your simulator","Choose a complete simulation, or prepare a reusable model first. A team project is optional while preparing CAD. Your progress is saved locally and can be resumed later.");
        var p=column();var goals=new JComboBox<>(new String[]{"Set up a simulation","Prepare a robot","Prepare a field"});goals.setSelectedIndex(controller.session.goal().equals("robot")?1:controller.session.goal().equals("field")?2:0);var r=row();r.add(new JLabel("What would you like to do?"));r.add(goals);p.add(r);
        r=row();r.add(new JLabel(controller.session.project()==null?"No team project selected — you can prepare models now.":"Team project: "+controller.session.project()));button(r,"Choose project…",this::project);p.add(r);
        r=row();button(r,"Continue saved setup…",()->{Path path=selectSession();if(path!=null)work("Restoring your saved setup…",()->{controller.resume(path);return null;},()->navigate(controller.session.firstIncomplete()));});p.add(r);
        p.add(new JLabel("Next: choose a supported CAD ZIP or saved model. Generic field needs no import."));content.add(p);
        leave=()->{try{controller.session.start(goals.getSelectedIndex()==1?"robot":goals.getSelectedIndex()==2?"field":"simulation",controller.session.project());}catch(Exception e){throw new IllegalArgumentException(e.getMessage(),e);}};
    }
    private Path selectSession(){try{Path folder=controller.models.library.resolve("sessions");List<Path> files;try(var stream=Files.list(folder)){files=stream.filter(p->p.toString().endsWith(".json")&&!p.getFileName().toString().contains("-view")).sorted(Comparator.comparingLong((Path p)->{try{return Files.getLastModifiedTime(p).toMillis();}catch(Exception e){return 0;}}).reversed()).toList();}files=files.stream().filter(p->!p.equals(controller.session.file)).toList();if(files.isEmpty()){status.setText("No earlier setup sessions yet. Use Save and close to keep this one.");return null;}var choices=files.stream().map(p->{try{var d=MiniJson.parseObject(Files.readString(p));return d.get("goal")+" · "+d.get("current")+" · "+p.getFileName();}catch(Exception e){return p.getFileName().toString();}}).toArray(String[]::new);Object value=JOptionPane.showInputDialog(window,"Choose the setup to resume","Saved setups",JOptionPane.QUESTION_MESSAGE,null,choices,choices[0]);return value==null?null:files.get(Arrays.asList(choices).indexOf(value));}catch(Exception e){failure(e);return null;}}
    private Path revision(String kind){try{var paths=new ArrayList<Path>();var labels=new ArrayList<String>();for(Path p:controller.models.revisions()){var d=MiniJson.parseObject(Files.readString(p));if(!kind.equals(d.get("model_kind")))continue;paths.add(p);labels.add(d.get("name")+" · "+FieldPackage.map(d.get("review")).get("state")+" · "+d.get("revision_id"));}if(paths.isEmpty()){status.setText("No saved "+kind+" models yet. Import its CAD ZIP first.");return null;}Object chosen=JOptionPane.showInputDialog(window,"Choose "+kind+" settings","Model library",JOptionPane.QUESTION_MESSAGE,null,labels.toArray(),labels.get(0));return chosen==null?null:paths.get(labels.indexOf(chosen));}catch(Exception e){failure(e);return null;}}
    private void sourcePage() throws Exception {
        String kind=step.kind();header("Choose your "+kind,"Select a ZIP containing one URDF and its referenced STL files, or reuse a saved model. Identical reviewed CAD reuses its settings and calibration. Changed CAD gets migration choices in Parts and movement.");
        var p=column();var r=row();button(r,"Import CAD ZIP…",()->importCAD(kind));button(r,"Use saved model…",()->{Path selected=revision(kind);if(selected!=null)load(kind,"saved",selected,null);});button(r,"Import profile bundle…",()->{Path path=choose("Choose a portable model profile ZIP",false,false);if(path!=null)load(kind,"bundle",path,null);});p.add(r);
        r=row();button(r,"Capture existing preparation…",()->{Path path=choose(kind.equals("robot")?"Choose prepared project's sim.config":"Choose prepared BIOBUZZ field.json",false,false);if(path!=null)load(kind,"capture",kind.equals("robot")?path.getParent():path,null);});if(kind.equals("field")&&controller.session.goal().equals("simulation"))button(r,"Use generic field — no CAD import",()->{try{controller.session.genericField();navigate(step);}catch(Exception e){failure(e);}});p.add(r);
        String ref=controller.session.reference(kind);
        if(ref!=null){if(ref.equals("generic"))p.add(new JLabel("Generic field selected: 3.6576 × 3.6576 m. Choose its piece mode in Scene."));else {var d=controller.session.profile(kind);int count=FieldPackage.map(d.get("entities")).size();p.add(new JLabel("Selected: "+d.get("name")+" · "+count+" CAD parts"));p.add(new JLabel(controller.session.ready(kind)?"Saved collision review is valid. Next skips completed model preparation.":"This model needs size, behavior and collision review before simulation."));var migration=FieldPackage.map(d.get("migration"));p.add(new JLabel(FieldPackage.maps(migration.get("decisions")).size()+" matched/migrated choices · "+FieldPackage.maps(migration.get("pending")).size()+" choices need your input"));r=row();button(r,"Change saved settings",()->work("Creating an editable draft…",()->{controller.edit(kind);return null;},()->navigate(new GuidedSetupSession.Step(kind,"scale"))));p.add(r);}}
        content.add(p);
    }
    private void importCAD(String kind){Path zip=choose("Choose "+kind+" URDF/STL ZIP",false,false);if(zip==null)return;Object answer=JOptionPane.showInputDialog(window,"Should this CAD reuse earlier settings?","Import settings",JOptionPane.QUESTION_MESSAGE,null,new String[]{"Reuse identical saved CAD automatically","Choose earlier settings for changed CAD","Generate fresh defaults"},"Reuse identical saved CAD automatically");if(answer==null)return;Path reuse=answer.toString().startsWith("Choose")?revision(kind):null;if(answer.toString().startsWith("Choose")&&reuse==null)return;load(kind,answer.toString().startsWith("Generate")?"fresh":"cad",zip,reuse);}
    private void load(String kind,String operation,Path input,Path reuse){work("Reading source and preparing geometry…",()->{controller.load(kind,operation,input,reuse);return null;},()->{status.setText("Model loaded. Review its summary, then choose Next.");navigate(step);});}
    private void scalePage() throws Exception {
        profile=controller.session.profile(step.kind());header("Check size and orientation","Compare the dimensions with your actual model. A 45 cm robot should not appear as 0.45 mm or 450 m. Choose source units before tuning physical dimensions. The preview uses actual meters, a grid and labeled coordinate directions.");
        var p=new JPanel(new BorderLayout(8,8));var controls=column();var r=row();var units=new JComboBox<>(new String[]{"m","mm","in"});units.setSelectedItem(FieldPackage.map(profile.get("parameters")).get("length_unit"));r.add(new JLabel("Source length units:"));r.add(units);button(r,"Apply units",()->work("Converting source dimensions…",()->{controller.units(step.kind(),units.getSelectedItem().toString());return null;},()->navigate(step)));button(r,"Open size / collision preview",()->preview());controls.add(r);
        var dimensions=new JLabel("Reading metric dimensions…");controls.add(dimensions);r=row();var forward=new JComboBox<>(new String[]{"CAD +X points forward","CAD +Y points forward","CAD -X points forward","CAD -Y points forward"});r.add(forward);button(r,"Apply forward direction",()->{double[] angles={0,-Math.PI/2,Math.PI,Math.PI/2};FieldPackage.map(profile.get("parameters")).put("origin_rpy_rad",List.of(0.,0.,angles[forward.getSelectedIndex()]));changed();});controls.add(r);p.add(controls,BorderLayout.NORTH);
        parameters=new GuidedParameterPanel(controller,step.kind(),profile,profile.get("parameters"),"parameters","scale",this::changed);p.add(parameters);var confirm=new JCheckBox("I checked that the model's size and orientation make sense.");p.add(confirm,BorderLayout.SOUTH);content.add(p);
        boolean adapter="biobuzz".equals(profile.get("adapter"));if(adapter){units.setEnabled(false);controls.remove(controls.getComponent(2));confirm.setText("I checked the captured field's fixed metric dimensions and orientation.");p.remove(parameters);p.add(new JLabel("This captured field retains its authored metric assembly corrections. Use Advanced settings to inspect them."));}
        leave=()->{parameters.commit();if(!confirm.isSelected()&&!controller.session.ready(step.kind()))throw new IllegalArgumentException("Check the dimensions/preview and confirm the size before continuing.");};
        work("Reading prepared metric dimensions…",()->{String text=controller.dimensions(step.kind());SwingUtilities.invokeLater(()->dimensions.setText(text));return null;},()->status.setText("Check the dimensions and confirm before Next."));
    }
    private void partsPage() throws Exception {
        profile=controller.session.profile(step.kind());header("Identify parts and movement","Welded parts move together as one body. Choose how parts behave and how joints move. For a robot, map movable joints to motors/servos from your project; this can be deferred when saving only a model. For a field, distinguish fixed structure, mechanisms and loose pieces.");
        var p=new JPanel(new BorderLayout(8,8));var controls=column();migration(controls);var r=row();r.add(new JLabel(controller.session.project()==null?"Hardware mapping deferred — no project selected.":"Hardware choices from "+controller.session.project().getFileName()));button(r,"Choose project…",this::project);button(r,"Advanced settings",this::advanced);controls.add(r);p.add(controls,BorderLayout.NORTH);
        if("biobuzz".equals(profile.get("adapter"))){p.add(new JLabel("Captured BIOBUZZ: authored structure, loose pieces and passive HIVES are preserved. Review actual contact parameters in Physics assumptions."));}
        else {
            var names=FieldPackage.map(profile.get("entities")).keySet().toArray(String[]::new);var select=new JComboBox<>(names);var panel=new JPanel(new BorderLayout());var actions=row();actions.add(new JLabel("Part:"));actions.add(select);button(actions,"Focus this body",()->{try{controller.focus(select.getSelectedItem().toString());preview();}catch(Exception e){failure(e);}});button(actions,"Bind motor / servo…",()->bind(select.getSelectedItem().toString()));if(step.kind().equals("robot")){button(actions,"Add differential drive…",()->runtime(true));button(actions,"Add motor intake…",()->runtime(false));}panel.add(actions,BorderLayout.NORTH);
            Runnable showPart=()->{String name=select.getSelectedItem().toString();Object settings=FieldPackage.map(FieldPackage.map(profile.get("entities")).get(name)).get("settings");parameters=new GuidedParameterPanel(controller,step.kind(),profile,settings,"entities/"+pointer(name)+"/settings","parts",this::changed);panel.add(parameters);panel.revalidate();panel.repaint();};select.addActionListener(e->{if(parameters!=null){parameters.commit();panel.remove(parameters);}showPart.run();});showPart.run();p.add(panel);
        }
        content.add(p);leave=()->{if(parameters!=null)parameters.commit();};
    }
    private void migration(JPanel p){var migration=FieldPackage.map(profile.get("migration"));var pending=FieldPackage.maps(migration.get("pending"));if(pending.isEmpty()){p.add(new JLabel("No unresolved migration choices."));return;}var item=pending.get(0);p.add(new JLabel(pending.size()+" migration choices remain. "+item.get("reason")));if(item.get("new")!=null)p.add(new JLabel("Changed part: "+item.get("new")));if(item.get("removed")!=null){var removed=new JTextArea("Earlier parts without retained settings: "+item.get("removed"),2,60);removed.setEditable(false);removed.setLineWrap(true);removed.setWrapStyleWord(true);removed.setOpaque(false);p.add(new JScrollPane(removed));}var r=row();var options=new JComboBox<>(((List<?>)item.get("options")).toArray());r.add(options);button(r,"Use this resolution",()->work("Migrating saved settings…",()->{controller.resolve(step.kind(),0,options.getSelectedItem().toString());return null;},()->navigate(step)));p.add(r);}
    private void bind(String name){try{var settings=FieldPackage.map(FieldPackage.map(FieldPackage.map(profile.get("entities")).get(name)).get("settings"));if(settings.get("joint")==null||"fixed".equals(FieldPackage.map(settings.get("joint")).get("type")))throw new IllegalArgumentException("Choose a movable child joint first. Change Joint movement if the CAD joint should rotate or slide.");var names=controller.hardware(null);if(names.isEmpty())throw new IllegalArgumentException("Choose a project with motor/servo names, or defer hardware mapping and save the model first.");Object selected=JOptionPane.showInputDialog(window,"Choose hardware driving this joint. Verify gearing and direction afterward.","Motor / servo binding",JOptionPane.QUESTION_MESSAGE,null,names.toArray(),names.get(0));if(selected==null)return;settings.put("actuators",new ArrayList<>(List.of(new LinkedHashMap<>(Map.of("name",selected.toString(),"mechanicalReduction",1.)))));var provenance=FieldPackage.map(profile.get("provenance"));String binding="entities/"+pointer(name)+"/settings/actuators/0/";provenance.put(binding+"name","user supplied");provenance.put(binding+"mechanicalReduction","default provisional");if(controller.hardware(RobotConfigXml.DeviceType.SERVO).contains(selected.toString())){var runtime=FieldPackage.map(profile.get("runtime"));runtime.putIfAbsent("servoPhysics",new LinkedHashMap<String,Object>());FieldPackage.map(runtime.get("servoPhysics")).putIfAbsent(selected.toString(),new LinkedHashMap<>(Map.of("stall_torque_nm",.2,"no_load_speed_rad_s",3.,"travel_rad",Math.PI,"position_gain_per_s",4.,"velocity_gain_nm_per_rad_s",.05,"deadband_rad",.01)));}changed();compileAndReload();}catch(Exception e){failure(e);}}
    private void runtime(boolean drive){try{var names=controller.hardware(RobotConfigXml.DeviceType.MOTOR);if(names.isEmpty())throw new IllegalArgumentException("Choose a project containing motor names first.");Object first=JOptionPane.showInputDialog(window,drive?"Left motor":"Intake motor","Motor model",JOptionPane.QUESTION_MESSAGE,null,names.toArray(),names.get(0));if(first==null)return;var runtime=FieldPackage.map(profile.get("runtime"));if(drive){Object second=JOptionPane.showInputDialog(window,"Right motor","Motor model",JOptionPane.QUESTION_MESSAGE,null,names.toArray(),names.get(0));if(second==null)return;if(second.equals(first))throw new IllegalArgumentException("Choose distinct left and right motors.");runtime.remove("drive_geometry");runtime.put("drive",new LinkedHashMap<>(Map.of("type","differential","left_motor",first,"right_motor",second,"track_width_m",.38,"wheel_radius_m",.045,"left_shaft_sign",-1,"right_shaft_sign",1)));}else runtime.put("intake",new LinkedHashMap<>(Map.of("motor",first,"shaft_sign",1,"min_speed_rad_s",1.,"point_xyz_m",new ArrayList<>(List.of(.25,0.,.06)),"capture_radius_m",.12)));changed();compileAndReload();}catch(Exception e){failure(e);}}
    private void measureRobot(){
        try{if(parameters!=null)parameters.commit();debounce.stop();
            RobotMeasurementGuide.Snapshot[] snapshot=new RobotMeasurementGuide.Snapshot[1];
            work("Reading saved weight, wheels and motor bindings…",()->{controller.compile("robot");snapshot[0]=RobotMeasurementGuide.read(controller);return null;},()->{
                var result=RobotMeasurementGuide.show(window,snapshot[0]);if(result==null){status.setText("Measurements unchanged.");return;}
                work("Saving measured robot settings…",()->{controller.measurements(result.entry());return null;},()->{
                    navigate(new GuidedSetupSession.Step("robot",result.openBindings()?"parts":"physics"));
                    status.setText(result.entry().empty()?"Review and map the motor bindings.":"Measurements saved in the robot draft. Recheck assumptions and collisions before saving a reviewed revision.");
                });
            });
        }catch(Exception e){failure(e);}
    }
    private void physicsPage() throws Exception {
        profile=controller.session.profile(step.kind());header("Review the physical assumptions","CAD often omits mass and contact properties. Generated values are provisional starting points. Keep them for now or enter known values; saving defaults does not label them measured. Check openings when choosing box shapes. Welded parts share one body's contact material.");
        var panel=new JPanel(new BorderLayout(8,8));var controls=row();var choices=new ArrayList<String>();choices.add("Shared defaults");if("biobuzz".equals(profile.get("adapter")))choices.add("Authored field contact / mechanism data");else choices.addAll(FieldPackage.map(profile.get("entities")).keySet());choices.add("Runtime / calibrated settings");var select=new JComboBox<>(choices.toArray(String[]::new));controls.add(new JLabel("Settings for:"));controls.add(select);button(controls,"Advanced settings",this::advanced);button(controls,"Open collision preview",this::preview);if(step.kind().equals("robot"))button(controls,"Measure robot and verify motors…",this::measureRobot);panel.add(controls,BorderLayout.NORTH);
        Runnable show=()->{String selected=select.getSelectedItem().toString();Object values;String path;if(selected.equals("Shared defaults")){values=profile.get("parameters");path="parameters";}else if(selected.equals("Runtime / calibrated settings")){values=profile.get("runtime");path="runtime";}else if(selected.startsWith("Authored field")){values=FieldPackage.map(profile.get("runtime")).get("field_manifest");path="runtime/field_manifest";}else {values=FieldPackage.map(FieldPackage.map(profile.get("entities")).get(selected)).get("settings");path="entities/"+pointer(selected)+"/settings";}
            parameters=new GuidedParameterPanel(controller,step.kind(),profile,values,path,"physics",this::changed);panel.add(parameters);panel.revalidate();panel.repaint();};select.addActionListener(e->{if(parameters!=null){parameters.commit();panel.remove(parameters);}show.run();});show.run();var keep=new JCheckBox("I reviewed the assumptions and will keep any remaining defaults provisional.");panel.add(keep,BorderLayout.SOUTH);content.add(panel);leave=()->{parameters.commit();if(!keep.isSelected()&&!controller.session.ready(step.kind()))throw new IllegalArgumentException("Review the assumptions and confirm that remaining defaults are provisional.");};
    }
    private void reviewPage() throws Exception {
        profile=controller.session.profile(step.kind());header("Review collision geometry and save","The outlines show what objects actually collide with: cyan is moving, orange is fixed, magenta is the focused body. Inspect openings, thin surfaces, wheels and the floor. A native construction check tests consistency; it does not measure the real robot's friction or rubber properties.");
        var p=column();var r=row();button(r,"Open live collision preview",this::preview);button(r,"Advanced settings",this::advanced);p.add(r);var boxes=new ArrayList<JCheckBox>();for(String text:List.of("I inspected the collision shapes, openings and thin surfaces.","I checked the dimensions, orientation and floor/wheel relationships.","I understand which mass/contact/mechanism values remain provisional.")){var b=new JCheckBox(text);boxes.add(b);p.add(b);}r=row();button(r,"Run checks and save reviewed model",()->work("Checking native bodies and saving this reviewed revision…",()->{controller.review(step.kind(),boxes.stream().allMatch(JCheckBox::isSelected));return null;},()->navigate(step)));p.add(r);
        p.add(new JLabel(controller.session.ready(step.kind())?"This saved model is collision-reviewed and reusable. Choose Next.":"A draft is saved automatically. Complete the review and save before Next."));var pending=FieldPackage.maps(FieldPackage.map(profile.get("migration")).get("pending"));if(!pending.isEmpty())p.add(new JLabel("Resolve "+pending.size()+" migration choices in Parts and movement first."));content.add(p);
    }
    private void motionPage() {
        header("Compare the robot's movements with your expectations","Watch short drivetrain movements, then each powered mechanism moving separately. Differential/tank drive goes forward/back and turns; configured Mecanum also strafes. Capabilities come from your joint and motor settings. Use this to spot wrong axes, missing bindings, limits or collision problems before review.");
        var p=new JPanel(new BorderLayout(8,8));var summary=new JTextArea("Reading configured movements…",12,70);summary.setEditable(false);summary.setLineWrap(true);summary.setWrapStyleWord(true);p.add(new JScrollPane(summary));var actions=row();button(actions,"Run motion demo…",this::motionDemo);button(actions,"View demo results",this::motionResults);button(actions,"Open collision preview",this::preview);button(actions,"Back to motor bindings",()->navigate(new GuidedSetupSession.Step("robot","parts")));p.add(actions,BorderLayout.SOUTH);content.add(p);
        work("Reading configured drivetrain and mechanisms…",()->{try{var setup=controller.motionSetup();SwingUtilities.invokeLater(()->summary.setText(setup.hardwareLabel()+"\n\n"+setup.plan().summary()+"\n\nSpace pauses, S stops, R replays; Esc closes. The neutral demo floor is separate from your field scene. Native contacts can block movement. Compare each visible result with your actual robot.\n\nYou may choose Next and return later if hardware mapping is deferred. Collision review still follows this step."));}catch(Exception e){SwingUtilities.invokeLater(()->summary.setText("Motion setup needs attention: "+friendly(e)+"\n\nCorrect Parts / Physics assumptions, or choose Next and return later. You can still inspect CAD in the collision preview."));}return null;},()->status.setText("Run the demo and compare movements; Next continues to collision review."));
    }
    private void motionDemo(){work("Launching the robot motion demo…",()->{controller.motionDemo();return null;},()->status.setText("Motion demo opened. Watch the movements; return to View demo results afterward."));}
    private void motionResults(){String[] result=new String[1];work("Reading motion observations…",()->{result[0]=controller.motionResults();return null;},()->{var text=new JTextArea(result[0],20,85);text.setEditable(false);text.setLineWrap(true);text.setWrapStyleWord(true);JOptionPane.showMessageDialog(window,new JScrollPane(text),"Robot motion observations",JOptionPane.INFORMATION_MESSAGE);});}
    private void changed(){try{controller.update(step.kind(),profile);debounce.restart();status.setText("Draft saved. Preparing the edited values shortly…");}catch(Exception e){failure(e);}}
    private void compileChanges(){if(busy||profile==null)return;work("Preparing edited settings…",()->{controller.compile(step.kind());return null;},()->status.setText("Edits prepared. Preview will reload; complete the required review."));}
    private void compileAndReload(){work("Preparing changed settings…",()->{controller.compile(step.kind());return null;},()->navigate(step));}
    private void preview(){if(parameters!=null)parameters.commit();work("Preparing native preview…",()->{controller.preview(step.kind());return null;},()->status.setText("Preview opened. Inspect actual native shapes and return to this step."));}
    private void advanced(){if(busy)return;try{if(parameters!=null)parameters.commit();String kind=step.kind();work("Opening the full settings editor…",()->{controller.edit(kind);return null;},()->{busy=true;setControls(content,false);next.setEnabled(false);back.setEnabled(false);close.setEnabled(false);sidebar.setEnabled(false);ModelPreparationEditor.editDraft(controller.models.library,controller.session.project(),controller.session.modelPath(kind),()->{busy=false;setControls(content,true);close.setEnabled(true);sidebar.setEnabled(true);navigate(step);});});}catch(Exception e){failure(e);}}
    private static String pointer(String value){return value.replace("~","~0").replace("/","~1");}
    private void scenePage() throws Exception {
        header("Arrange the field and robot","Field only includes the floor, walls and mechanisms. Field with game pieces also includes your selected movable pieces. Set starting positions in meters, inspect the combined scene, then Check scene. Reset in the simulator restores these poses.");
        scene=controller.session.scenePath()!=null&&Files.isRegularFile(controller.session.scenePath())?MiniJson.parseObject(Files.readString(controller.session.scenePath())):controller.newScene();
        var readiness=new JLabel();var panel=new JPanel(new BorderLayout(8,8));var top=column();var r=row();var mode=new JComboBox<>(new String[]{"Field only","Field with game pieces"});mode.setSelectedIndex("game-pieces".equals(scene.get("mode"))?1:0);var set=new JComboBox<>(new String[]{"BIOBUZZ practice balls","Practice torus"});set.setSelectedIndex("torus".equals(scene.get("piece_set"))?1:0);r.add(mode);if("generic".equals(controller.session.reference("field")))r.add(set);r.add(new JLabel("Robot and field retain their actual metric scale."));top.add(r);
        r=row();var xyz=FieldPackage.vector(scene.get("robot_start_xyz_m"),3);JSpinner[] pose=new JSpinner[4];for(int i=0;i<4;i++){pose[i]=new JSpinner(new SpinnerNumberModel(i<3?xyz[i]:FieldPackage.num(scene,"robot_start_yaw_rad"),-100.,100.,.01));r.add(new JLabel(new String[]{"Robot X (m)","Robot Y (m)","Height Z (m)","Yaw (rad)"}[i]));r.add(pose[i]);}top.add(r);panel.add(top,BorderLayout.NORTH);
        var pieces=new DefaultTableModel(new String[]{"Piece","X (m)","Y (m)","Height Z (m)","Roll (rad)","Pitch (rad)","Yaw (rad)","Enabled","Template"},0){public boolean isCellEditable(int row,int col){return col>0&&col<8;}public Class<?> getColumnClass(int col){return col==7?Boolean.class:Object.class;}};var templateNames=controller.sourcePieces(set.getSelectedIndex()==1?"torus":"biobuzz");var table=new JTable(pieces);table.setRowHeight(27);
        var labels=new javax.swing.table.DefaultTableCellRenderer(){@Override public Component getTableCellRendererComponent(JTable t,Object value,boolean selected,boolean focused,int row,int col){String source=pieces.getValueAt(row,8).toString();String name=FieldPackage.map(templateNames.get(source)).getOrDefault("label",source).toString();String text=col==8?name:value.toString().equals(source)?name:name+" · copy "+value.toString().substring(0,Math.min(8,value.toString().length()));var cell=super.getTableCellRendererComponent(t,text,selected,focused,row,col);setToolTipText(value.toString());return cell;}};table.getColumnModel().getColumn(0).setCellRenderer(labels);table.getColumnModel().getColumn(8).setCellRenderer(labels);table.getColumnModel().getColumn(0).setPreferredWidth(180);table.getColumnModel().getColumn(8).setPreferredWidth(160);
        java.util.function.Consumer<Map<String,Object>> fill=layout->{boolean wasRendering=rendering;rendering=true;try{pieces.setRowCount(0);for(var entry:layout.entrySet()){var p=FieldPackage.map(entry.getValue());var a=FieldPackage.vector(p.get("xyz_m"),3);var b=FieldPackage.vector(p.get("rpy_rad"),3);pieces.addRow(new Object[]{entry.getKey(),a[0],a[1],a[2],b[0],b[1],b[2],p.getOrDefault("enabled",true),p.getOrDefault("source_id",entry.getKey())});}}finally{rendering=wasRendering;}};
        fill.accept(FieldPackage.map(scene.get("pieces")));panel.add(new JScrollPane(table));var bottom=column();r=row();button(r,"Use model piece layout",()->{try{fill.accept(controller.sourcePieces(set.getSelectedIndex()==1?"torus":"biobuzz"));saveLayout(mode,set,pose,table,pieces);}catch(Exception e){failure(e);}});button(r,"Duplicate selected piece",()->{int selected=table.getSelectedRow();if(selected<0){status.setText("Select a piece row to duplicate it.");return;}Object[] values=new Object[9];for(int i=0;i<9;i++)values[i]=pieces.getValueAt(selected,i);values[0]="scene-"+UUID.randomUUID();values[1]=Double.parseDouble(values[1].toString())+(values[8].equals("practice-torus")?.3:.12);values[7]=true;pieces.addRow(values);});button(r,"Disable selected piece",()->{int selected=table.getSelectedRow();if(selected>=0)pieces.setValueAt(false,selected,7);});button(r,"Map missing piece template…",()->{int selected=table.getSelectedRow();if(selected<0)return;try{var sources=controller.sourcePieces(set.getSelectedIndex()==1?"torus":"biobuzz");var ids=new ArrayList<>(sources.keySet());var choices=ids.stream().map(id->FieldPackage.map(sources.get(id)).getOrDefault("label",id)+" · "+id).toArray();if(choices.length==0)throw new IllegalArgumentException("This field model has no piece templates. Disable the row or select a model with pieces.");Object picked=JOptionPane.showInputDialog(window,"Choose the source piece for this saved placement","Piece migration",JOptionPane.QUESTION_MESSAGE,null,choices,choices[0]);if(picked!=null)pieces.setValueAt(ids.get(Arrays.asList(choices).indexOf(picked)),selected,8);}catch(Exception e){failure(e);}});bottom.add(r);
        r=row();button(r,"Preview combined scene",()->{try{saveLayout(mode,set,pose,table,pieces);work("Opening the unpowered scene preview…",()->{controller.scenePreview();return null;},()->status.setText("Inspect positions, then use Check scene."));}catch(Exception e){failure(e);}});button(r,"Check scene",()->{try{saveLayout(mode,set,pose,table,pieces);work("Checking scene identity, bounds and native contacts…",()->{controller.saveScene(scene,true);return null;},()->{readiness.setText("Saved placement checks are valid.");status.setText("Scene checks passed. Choose Next to finish.");});}catch(Exception e){failure(e);}});bottom.add(r);readiness.setText(controller.session.sceneReady()?"Saved placement checks are valid.":"Scene placement needs checking before finishing.");bottom.add(readiness);panel.add(bottom,BorderLayout.SOUTH);content.add(panel);
        Runnable changed=()->{if(rendering||busy)return;try{saveLayout(mode,set,pose,table,pieces);readiness.setText(controller.session.sceneReady()?"Saved placement checks are valid.":"Scene placement needs checking before finishing.");status.setText(controller.session.sceneReady()?"Saved placement checks are valid.":"Layout saved. Use Check scene for these placements.");refreshNavigation();}catch(Exception e){readiness.setText("Scene placement needs valid numeric values.");status.setText("Enter valid numeric placements before continuing.");}};for(var spinner:pose)spinner.addChangeListener(e->changed.run());pieces.addTableModelListener(e->changed.run());mode.addActionListener(e->{if(mode.getSelectedIndex()==1&&pieces.getRowCount()==0)try{fill.accept(controller.sourcePieces(set.getSelectedIndex()==1?"torus":"biobuzz"));}catch(Exception ex){failure(ex);}changed.run();});set.addActionListener(e->{if(rendering||busy)return;try{fill.accept(controller.sourcePieces(set.getSelectedIndex()==1?"torus":"biobuzz"));changed.run();}catch(Exception ex){failure(ex);}});leave=()->saveLayout(mode,set,pose,table,pieces);
    }
    private void saveLayout(JComboBox<String> mode,JComboBox<String> set,JSpinner[] pose,JTable table,DefaultTableModel pieces){
        if(savingLayout)return;savingLayout=true;try{if(table.isEditing())table.getCellEditor().stopCellEditing();for(var p:pose)p.commitEdit();scene.put("mode",mode.getSelectedIndex()==0?"field-only":"game-pieces");scene.put("piece_set",set.getSelectedIndex()==1?"torus":"biobuzz");scene.put("robot_start_xyz_m",List.of(pose[0].getValue(),pose[1].getValue(),pose[2].getValue()));scene.put("robot_start_yaw_rad",pose[3].getValue());var layout=new LinkedHashMap<String,Object>();for(int r=0;r<pieces.getRowCount();r++){var xyz=new ArrayList<Double>();var rpy=new ArrayList<Double>();for(int c=1;c<=3;c++){xyz.add(Double.parseDouble(pieces.getValueAt(r,c).toString()));rpy.add(Double.parseDouble(pieces.getValueAt(r,c+3).toString()));}layout.put(pieces.getValueAt(r,0).toString(),Map.of("xyz_m",xyz,"rpy_rad",rpy,"enabled",pieces.getValueAt(r,7),"source_id",pieces.getValueAt(r,8)));}scene.put("pieces",layout);controller.saveScene(scene,false);}catch(Exception e){throw new IllegalArgumentException(e.getMessage(),e);}finally{savingLayout=false;}
    }
    private void finishPage() throws Exception {
        header("Your reusable setup","Models and scene layout are saved separately. Collision review confirms inspected geometry and native consistency; provisional settings can still be tuned later. Connect a team project to validate hardware names and choose runnable robot code.");
        var p=column();for(String kind:List.of("robot","field")){if(controller.session.reference(kind)==null)continue;if("generic".equals(controller.session.reference(kind)))p.add(new JLabel("Field: generic, no CAD import"));else {var d=controller.session.profile(kind);p.add(new JLabel(Character.toUpperCase(kind.charAt(0))+kind.substring(1)+": "+d.get("name")+" · "+(controller.session.ready(kind)?"collision-reviewed":"needs review")));var summary=new JTextArea(controller.provisionalSummary(kind),2,60);summary.setLineWrap(true);summary.setWrapStyleWord(true);summary.setEditable(false);summary.setOpaque(false);p.add(summary);var r=row();button(r,"Export "+kind+" profile…",()->{Path out=choose("Export ZIP — includes copied source CAD, prepared assets and settings",true,false);if(out!=null)work("Exporting portable model bundle…",()->controller.models.run("export",controller.session.modelPath(kind).toString(),out.toString()),()->status.setText("Portable bundle exported, including source CAD."));});if(kind.equals("robot")){button(r,"Measure robot and verify motors…",this::measureRobot);button(r,"Run motion demo…",this::motionDemo);button(r,"View demo results",this::motionResults);}p.add(r);}}
        if(controller.session.scenePath()!=null)p.add(new JLabel("Scene: "+controller.session.scenePath()+" · "+(controller.session.sceneReady()?"placement checked":"needs placement check")));
        p.add(new JLabel("Provisional CAD/default values are retained with the model; measured calibration is preserved when available."));var r=row();r.add(new JLabel(controller.session.project()==null?"No project: your model can be finished and reused later.":"Project: "+controller.session.project()));button(r,"Choose project…",this::project);p.add(r);
        var policy=new JComboBox<>(new String[]{"Use saved model physics","Keep existing project physics"});policy.setSelectedIndex("project".equals(controller.session.data.get("model_settings"))?1:0);r=row();r.add(new JLabel("If project and model settings overlap:"));r.add(policy);p.add(r);
        var opmodes=new JComboBox<String>();if(controller.session.data.get("opmodes") instanceof List<?> list)for(Object item:list)opmodes.addItem(item.toString());r=row();button(r,"Check project and find OpModes",()->work("Checking hardware and compiling/discovering team code…",()->{controller.checkProject(policy.getSelectedIndex()==0?"profile":"project");return null;},()->navigate(step)));r.add(opmodes);p.add(r);
        r=row();button(r,"Use saved setup in project",()->work("Validating and applying saved setup…",()->{controller.applyProject(policy.getSelectedIndex()==0?"profile":"project");return null;},()->status.setText("Saved setup selected in the project.")));
        if(controller.session.goal().equals("simulation"))button(r,"Use and run selected OpMode",()->{if(opmodes.getSelectedItem()==null){status.setText("Check the project to discover available OpModes first.");return;}work("Validating setup and launching the selected OpMode…",()->{controller.applyProject(policy.getSelectedIndex()==0?"profile":"project");ModelEditorController.javaProcess(SimulatorApp.class,List.of(controller.session.project().toString(),opmodes.getSelectedItem().toString()),true);return null;},()->status.setText("Selected OpMode launched. This action starts TeamCode."));});p.add(r);content.add(p);
    }
    private void advance(){if(busy)return;try{leave.run();if(step.page().equals("finish")){if(!controller.session.complete(step)){navigate(controller.session.firstIncomplete());return;}controller.session.data.put("finished",true);controller.session.save();window.dispose();return;}
        if(Set.of("scale","parts","physics").contains(step.page()))work("Preparing and checking this step…",()->{controller.compile(step.kind());if(step.page().equals("parts")&&!FieldPackage.maps(FieldPackage.map(controller.session.profile(step.kind()).get("migration")).get("pending")).isEmpty())throw new IllegalArgumentException("Resolve the migration choices on this page before continuing.");controller.session.acknowledge(step);return null;},this::nextStep);
        else {if(step.page().equals("motion"))controller.continueAfterMotion();if(!controller.session.complete(step))throw new IllegalArgumentException(switch(step.page()){case "source"->"Select a supported model or the generic field before continuing.";case "review"->"Inspect collisions, resolve migration choices, then Run checks and save reviewed model.";case "scene"->"Use Check scene to validate these exact placements before continuing.";default->"Complete this step before continuing.";});nextStep();}
        }catch(Exception e){failure(e);}}
    private void nextStep(){var steps=controller.session.steps();int i=steps.indexOf(step)+1;while(i<steps.size()-1&&controller.session.complete(steps.get(i)))i++;navigate(steps.get(Math.min(i,steps.size()-1)));}
    private void flushForNavigation(){if(parameters!=null)parameters.commit();if(step.page().equals("scene"))leave.run();if(step.page().equals("start"))leave.run();}
    private void saveClose(){if(busy){status.setText("Wait for the current operation to finish; your draft is retained.");return;}try{debounce.stop();if(parameters!=null)parameters.commit();if(step.page().equals("scene")||step.page().equals("start"))leave.run();controller.session.save();window.dispose();}catch(Exception e){failure(e);}}
}
