package simrunner;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.tree.*;
import java.awt.*;
import java.nio.file.*;
import java.util.*;
import java.util.List;
import simcore.MiniJson;
import simcore.RobotConfigXml;

/** Desktop preparation workflow. Saved revisions are opened as drafts, never edited in place. */
public final class ModelPreparationEditor {
    private final JFrame window=new JFrame("FTC Forge — prepare robot and field models");
    private final ModelEditorController controller;
    private final Path project;
    private Path draft,lastSaved;
    private Map<String,Object> profile;
    private final JTree tree=new JTree();
    private final JTextField search=new JTextField(22);
    private final JTextArea notes=new JTextArea(4,50);
    private final JLabel status=new JLabel("Import CAD, capture an existing prepared model, or open a saved revision.");
    private final Properties properties=new Properties();
    private final JTable table=new JTable(properties){
        @Override public javax.swing.table.TableCellEditor getCellEditor(int row,int col){
            if(col==1){var choices=options(properties.rows.get(row));if(choices!=null)return new DefaultCellEditor(new JComboBox<>(choices));if(properties.rows.get(row).value() instanceof Boolean)return new DefaultCellEditor(new JCheckBox());}
            return super.getCellEditor(row,col);
        }
    };
    private final javax.swing.Timer debounce=new javax.swing.Timer(600,e->compile());
    private boolean busy;
    private record Item(String label,Object value,String path){public String toString(){return label;}}
    private record Row(Object parent,Object key,Object value,String path){}
    @FunctionalInterface private interface Work{Object run()throws Exception;}
    public static void main(String[] args){Path library=Path.of(args.length>0?args[0]:".local/models");Path project=args.length>1?Path.of(args[1]).toAbsolutePath():null;SwingUtilities.invokeLater(()->new ModelPreparationEditor(library,project).show());}
    static void editDraft(Path library,Path project,Path draft,Runnable closed){
        var editor=new ModelPreparationEditor(library,project);editor.show();editor.open(draft);
        var buttons=new JPanel(new FlowLayout(FlowLayout.LEFT));editor.action(buttons,"Live collision preview",()->{try{ModelEditorController.javaProcess(ModelPreparationPreview.class,List.of(draft.toString()),true);}catch(Exception e){editor.error(e);}});editor.action(buttons,"Bind selected joint…",editor::bind);editor.action(buttons,"Add drive / intake…",editor::runtimeTemplate);
        var layout=(BorderLayout)editor.window.getContentPane().getLayout();editor.window.remove(layout.getLayoutComponent(BorderLayout.NORTH));editor.window.add(buttons,BorderLayout.NORTH);editor.window.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        editor.window.addWindowListener(new java.awt.event.WindowAdapter(){public void windowClosing(java.awt.event.WindowEvent event){if(editor.busy){editor.status.setText("Please wait for preparation to finish before closing.");return;}editor.debounce.stop();if(editor.table.isEditing())editor.table.getCellEditor().stopCellEditing();editor.debounce.stop();try{ProfileIO.save(draft,editor.profile);editor.work(()->{try{return editor.controller.run("compile",draft.toString());}catch(Exception e){return e;}},x->{editor.window.dispose();closed.run();});}catch(Exception e){editor.error(e);}}});editor.window.revalidate();
    }
    private ModelPreparationEditor(Path library,Path project){controller=new ModelEditorController(library);this.project=project;debounce.setRepeats(false);}
    private void show(){
        window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);window.setSize(1220,850);window.setLocationRelativeTo(null);
        JPanel actions=new JPanel(new FlowLayout(FlowLayout.LEFT));
        action(actions,"Guided setup…",()->{try{var command=new ArrayList<String>(List.of(Path.of(System.getProperty("java.home"),"bin/java").toString(),"-Xmx2g","-cp",System.getProperty("java.class.path"),GuidedSetupWizard.class.getName(),controller.library.toString()));if(project!=null)command.add(project.toString());new ProcessBuilder(command).inheritIO().start();}catch(Exception e){error(e);}});
        action(actions,"Import robot",()->importCAD("robot"));action(actions,"Import field",()->importCAD("field"));
        action(actions,"Open revision",()->openSaved(false));action(actions,"Alternative tuning",()->openSaved(true));
        action(actions,"Capture prepared model",this::capture);action(actions,"Import profile bundle",()->{Path p=choose(false,"Choose portable model ZIP");if(p!=null)work(()->controller.run("import-profile",p.toString(),controller.library.toString()),x->{lastSaved=null;open(x);});});
        action(actions,"Scene…",()->SceneEditor.show(controller,project,window));
        JPanel saves=new JPanel(new FlowLayout(FlowLayout.LEFT));
        action(saves,"Live collision preview",()->{if(draft!=null)work(()->{controller.run("compile",draft.toString());ModelEditorController.javaProcess(ModelPreparationPreview.class,List.of(draft.toString()),true);return null;},x->status.setText("Live preview opened. Edits reload the candidate geometry."));});
        action(saves,"Resolve migration…",this::resolve);action(saves,"Bind selected joint…",this::bind);action(saves,"Add drive / intake…",this::runtimeTemplate);
        action(saves,"Save draft",()->save(false));action(saves,"Save reviewed profile",()->save(true));
        action(saves,"Export profile…",()->{if(lastSaved==null){status.setText("Save a revision before exporting.");return;}Path p=choose(true,"Export ZIP (includes copied CAD and prepared geometry)");if(p!=null)work(()->controller.run("export",lastSaved.toString(),p.toString()),x->status.setText("Exported "+p));});
        action(saves,"Use robot in project",this::applyRobot);action(saves,"Use field in project",this::applyField);
        JPanel top=new JPanel(new GridLayout(0,1));top.add(actions);top.add(saves);window.add(top,BorderLayout.NORTH);
        JPanel left=new JPanel(new BorderLayout());left.add(search,BorderLayout.NORTH);left.add(new JScrollPane(tree));
        search.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){public void insertUpdate(javax.swing.event.DocumentEvent e){rebuild();}public void removeUpdate(javax.swing.event.DocumentEvent e){rebuild();}public void changedUpdate(javax.swing.event.DocumentEvent e){rebuild();}});
        tree.addTreeSelectionListener(e->{var n=(DefaultMutableTreeNode)tree.getLastSelectedPathComponent();if(n!=null&&n.getUserObject() instanceof Item i){properties.load(i.value,i.path);String text="Values and assumptions are saved in this revision. Dimensions: meters; joint xyz/prismatic limits: selected source units; angles: radians; mass: kg; inertia: kg·m².\n";if(i.path.startsWith("entities/")){String name=unpointer(i.path.split("/")[1]);var entity=FieldPackage.map(FieldPackage.map(profile.get("entities")).get(name));text+="Native body: "+bodyOwner(name)+" (materials apply to the whole body)\n"+ProfileIO.json(entity.get("assumptions"))+"\nCollision provenance: "+entity.get("provenance");}notes.setText(text);}});
        table.setRowHeight(25);table.getColumnModel().getColumn(0).setPreferredWidth(300);table.getColumnModel().getColumn(1).setPreferredWidth(200);
        notes.setEditable(false);notes.setLineWrap(true);notes.setWrapStyleWord(true);JPanel right=new JPanel(new BorderLayout());right.add(new JScrollPane(table));right.add(new JScrollPane(notes),BorderLayout.SOUTH);
        var split=new JSplitPane(JSplitPane.HORIZONTAL_SPLIT,left,right);split.setDividerLocation(340);window.add(split);window.add(status,BorderLayout.SOUTH);window.setVisible(true);
    }
    private void action(JPanel p,String name,Runnable r){JButton b=new JButton(name);b.addActionListener(e->{if(!busy){if(table.isEditing())table.getCellEditor().stopCellEditing();r.run();}});p.add(b);}
    private Path choose(boolean save,String title){var c=new JFileChooser(controller.library.toFile());c.setFileHidingEnabled(false);c.setDialogTitle(title);return (save?c.showSaveDialog(window):c.showOpenDialog(window))==JFileChooser.APPROVE_OPTION?c.getSelectedFile().toPath().toAbsolutePath():null;}
    private void work(Work work,java.util.function.Consumer<Object> done){if(busy)return;busy=true;table.setEnabled(false);status.setText("Preparing…");new SwingWorker<Object,Void>(){protected Object doInBackground()throws Exception{return work.run();}protected void done(){busy=false;table.setEnabled(true);try{done.accept(get());}catch(Exception e){error(e.getCause()==null?e:e.getCause());}}}.execute();}
    private void error(Throwable e){status.setText("Needs attention: "+e.getMessage());JOptionPane.showMessageDialog(window,e.getMessage(),"Preparation needs attention",JOptionPane.ERROR_MESSAGE);}
    private void open(Object result){try{debounce.stop();draft=Path.of(result.toString());profile=MiniJson.parseObject(Files.readString(draft));rebuild();status.setText(profile.get("name")+" | "+FieldPackage.map(profile.get("review")).get("state")+" | "+FieldPackage.maps(FieldPackage.map(profile.get("migration")).get("pending")).size()+" migration choices | "+draft);}catch(Exception e){error(e);}}
    private Path selectRevision(String title){try{var paths=controller.revisions();if(paths.isEmpty()){status.setText("No saved revisions yet.");return null;}String[] labels=paths.stream().map(p->{try{var m=MiniJson.parseObject(Files.readString(p));return m.get("name")+" | "+m.get("model_kind")+" | "+FieldPackage.map(m.get("review")).get("state")+" | "+m.get("revision_id");}catch(Exception e){return p.toString();}}).toArray(String[]::new);Object selected=JOptionPane.showInputDialog(window,title,"Model library",JOptionPane.QUESTION_MESSAGE,null,labels,labels[0]);return selected==null?null:paths.get(Arrays.asList(labels).indexOf(selected));}catch(Exception e){error(e);return null;}}
    private void openSaved(boolean duplicate){Path selected=selectRevision("Select saved tuning/revision");if(selected!=null){lastSaved=duplicate?null:selected;work(()->controller.run(duplicate?"duplicate":"edit",selected.toString(),controller.library.toString()),this::open);}}
    private void importCAD(String kind){Path zip=choose(false,"Choose "+kind+" URDF/STL ZIP");if(zip==null)return;Object option=JOptionPane.showInputDialog(window,"Reuse settings from an earlier version of this model?","Import",JOptionPane.QUESTION_MESSAGE,null,new String[]{"Automatically reuse identical CAD","Select saved settings for migration"},"Automatically reuse identical CAD");if(option==null)return;Path reuse=option.toString().startsWith("Select")?selectRevision("Select settings to migrate"):null;work(()->reuse==null?controller.run("import",zip.toString(),controller.library.toString(),"--kind",kind):controller.run("import",zip.toString(),controller.library.toString(),"--kind",kind,"--reuse",reuse.toString()),x->{Path result=Path.of(x.toString());if(result.toString().contains("/revisions/")){lastSaved=result;work(()->controller.run("edit",result.toString(),controller.library.toString()),this::open);}else {lastSaved=null;open(x);}});}
    private void capture(){Object kind=JOptionPane.showInputDialog(window,"Capture a working prepared model","Capture",JOptionPane.QUESTION_MESSAGE,null,new String[]{"Robot project (sim.config)","Prepared BIOBUZZ field.json"},"Robot project (sim.config)");if(kind==null)return;Path p=choose(false,kind.toString().startsWith("Robot")?"Select project's sim.config":"Select field.json");if(p!=null)work(()->controller.run(kind.toString().startsWith("Robot")?"capture-robot":"capture-field",(kind.toString().startsWith("Robot")?p.getParent():p).toString(),controller.library.toString()),x->{lastSaved=null;open(x);});}
    private void rebuild(){if(profile==null)return;properties.load(Map.of(),"");notes.setText("Select defaults, a part, or a runtime model to edit its values.");var root=new DefaultMutableTreeNode(profile.get("name"));add(root,"Defaults",profile.get("parameters"),"parameters");var entities=new DefaultMutableTreeNode("Parts / bodies");root.add(entities);if(!"biobuzz".equals(profile.get("adapter")))for(var e:FieldPackage.map(profile.get("entities")).entrySet())if(e.getKey().toLowerCase().contains(search.getText().toLowerCase()))add(entities,e.getKey(),FieldPackage.map(e.getValue()).get("settings"),"entities/"+pointer(e.getKey())+"/settings");add(root,"Runtime / contact models",profile.get("runtime"),"runtime");tree.setModel(new DefaultTreeModel(root));for(int i=0;i<Math.min(tree.getRowCount(),4);i++)tree.expandRow(i);}
    private void add(DefaultMutableTreeNode parent,String label,Object value,String path){
        var node=new DefaultMutableTreeNode(new Item(label,value,path));parent.add(node);
        if(value instanceof Map<?,?> m){for(var e:m.entrySet())if(e.getValue() instanceof Map || e.getValue() instanceof List<?> l&&!scalarList(l))add(node,e.getKey().toString(),e.getValue(),path+"/"+e.getKey());}
        else if(value instanceof List<?> l){for(int i=0;i<l.size();i++)if(l.get(i) instanceof Map || l.get(i) instanceof List<?> child&&!scalarList(child))add(node,Integer.toString(i),l.get(i),path+"/"+i);}
    }
    private static boolean scalarList(List<?> values){return values.stream().allMatch(v->!(v instanceof Map)&&!(v instanceof List));}
    private void compile(){if(draft==null||busy)return;try{ProfileIO.save(draft,profile);work(()->controller.run("compile",draft.toString()),x->{status.setText("Prepared latest settings. Live preview will reload; review is required after edits.");});}catch(Exception e){error(e);}}
    private void resolve(){if(profile==null)return;var pending=FieldPackage.maps(FieldPackage.map(profile.get("migration")).get("pending"));if(pending.isEmpty()){status.setText("No unresolved migration choices.");return;}var item=pending.get(0);var choices=((List<?>)item.get("options")).toArray();Object choice=JOptionPane.showInputDialog(window,item.get("reason")+"\nPart: "+item.get("new")+(item.containsKey("removed")?"\nRemoved: "+item.get("removed"):""),"Migration choice",JOptionPane.QUESTION_MESSAGE,null,choices,choices.length>0?choices[0]:null);if(choice!=null)work(()->{ProfileIO.save(draft,profile);return controller.run("resolve",draft.toString(),"0",choice.toString());},this::open);}
    private void save(boolean reviewed){if(draft==null)return;debounce.stop();try{ProfileIO.save(draft,profile);}catch(Exception e){error(e);return;}if(reviewed&&JOptionPane.showConfirmDialog(window,"Have you inspected the collision preview, including openings, thin surfaces, units and assumptions?\nA native construction check will run before this revision becomes ready.","Quick collision review",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION)return;work(()->{controller.run("compile",draft.toString());if(reviewed&&ModelEditorController.javaProcess(ModelValidation.class,List.of(draft.toString()),false).waitFor()!=0)throw new IllegalArgumentException("Native validation failed; inspect the preview and correct settings.");return reviewed?controller.run("save",draft.toString(),controller.library.toString(),"--reviewed"):controller.run("save",draft.toString(),controller.library.toString());},x->{lastSaved=Path.of(x.toString());status.setText("Saved "+(reviewed?"reviewed":"draft")+" revision: "+lastSaved);});}
    private void bind(){
        if(profile==null)return;var n=(DefaultMutableTreeNode)tree.getLastSelectedPathComponent();
        if(n==null||!(n.getUserObject() instanceof Item i)||!i.path.startsWith("entities/")){status.setText("Select a part with a movable joint first.");return;}
        var entity=FieldPackage.map(FieldPackage.map(profile.get("entities")).get(unpointer(i.path.split("/")[1])));var settings=FieldPackage.map(entity.get("settings"));
        if(settings.get("joint")==null){status.setText("This part is the assembly root; select a child joint.");return;}
        String[] names=hardware();if(names==null||names.length==0){status.setText("Open the editor with a team project to choose available motors/servos.");return;}
        Object choice=JOptionPane.showInputDialog(window,"Select hardware for this joint. Mechanical reduction is editable afterward.","Bind joint",JOptionPane.QUESTION_MESSAGE,null,names,names[0]);if(choice==null)return;
        try{var cfg=MiniJson.parseObject(Files.readString(project.resolve("sim.config")));var xml=RobotConfigXml.parse(project.resolve(cfg.get("robotConfig").toString()).toFile());if(xml.devices.stream().anyMatch(d->d.name.equals(choice.toString())&&RobotConfigXml.resolveType(d.tag)==RobotConfigXml.DeviceType.SERVO)){var runtime=FieldPackage.map(profile.get("runtime"));if(!runtime.containsKey("servoPhysics"))runtime.put("servoPhysics",new LinkedHashMap<String,Object>());FieldPackage.map(runtime.get("servoPhysics")).putIfAbsent(choice.toString(),new LinkedHashMap<>(Map.of("stall_torque_nm",.2,"no_load_speed_rad_s",3.,"travel_rad",Math.PI,"position_gain_per_s",4.,"velocity_gain_nm_per_rad_s",.05,"deadband_rad",.01)));}}catch(Exception failure){error(failure);return;}
        settings.put("actuators",new ArrayList<>(List.of(new LinkedHashMap<>(Map.of("name",choice.toString(),"mechanicalReduction",1.)))));entity.put("provenance","user supplied");rebuild();debounce.restart();
    }
    private void runtimeTemplate(){
        if(profile==null)return;String[] names=hardware();if(names==null||names.length==0){status.setText("Open with a team project to choose motor bindings.");return;}
        Object type=JOptionPane.showInputDialog(window,"Add editable defaults. Verify dimensions and signs before running.","Runtime model",JOptionPane.QUESTION_MESSAGE,null,new String[]{"Differential drive","Motor intake"},"Differential drive");if(type==null)return;
        Object first=JOptionPane.showInputDialog(window,type.toString().startsWith("Differential")?"Left motor":"Intake motor","Binding",JOptionPane.QUESTION_MESSAGE,null,names,names[0]);if(first==null)return;
        Map<String,Object> runtime=FieldPackage.map(profile.get("runtime"));
        if(type.toString().startsWith("Differential")){Object second=JOptionPane.showInputDialog(window,"Right motor","Binding",JOptionPane.QUESTION_MESSAGE,null,names,names[0]);if(second==null)return;runtime.remove("drive_geometry");runtime.put("drive",new LinkedHashMap<>(Map.of("type","differential","left_motor",first.toString(),"right_motor",second.toString(),"track_width_m",.38,"wheel_radius_m",.045,"left_shaft_sign",-1,"right_shaft_sign",1)));}
        else runtime.put("intake",new LinkedHashMap<>(Map.of("motor",first.toString(),"shaft_sign",1,"min_speed_rad_s",1.,"point_xyz_m",new ArrayList<>(List.of(.25,0.,.06)),"capture_radius_m",.12)));
        profile.put("review",new LinkedHashMap<>(Map.of("state","draft")));rebuild();debounce.restart();
    }
    private void applyRobot(){if(project==null||lastSaved==null){status.setText("Open the editor with a team project and save a reviewed robot first.");return;}try{var model=new ModelProfile(lastSaved,true);if(!model.kind.equals("robot"))throw new IllegalArgumentException("Select a robot revision");Object choice=JOptionPane.showInputDialog(window,"When project and model have overlapping physics settings, which should be used?","Apply robot",JOptionPane.QUESTION_MESSAGE,null,new String[]{"Saved model settings","Existing project settings"},"Saved model settings");if(choice==null)return;ProjectModelSelection.apply(project,model,choice.toString().startsWith("Saved")?"profile":"project");status.setText("Selected saved robot for "+project);}catch(Exception e){error(e);}}
    private void applyField(){if(project==null||lastSaved==null){status.setText("Open with a project and save a reviewed field first.");return;}try{var model=new ModelProfile(lastSaved,true);if(!model.kind.equals("field"))throw new IllegalArgumentException("Select a field revision");ProjectModelSelection.apply(project,model,"profile");status.setText("Selected saved field; use Scene… to choose its mode and piece layout.");}catch(Exception e){error(e);}}
    private static String pointer(String s){return s.replace("~","~0").replace("/","~1");}
    private static String unpointer(String s){return s.replace("~1","/").replace("~0","~");}
    private String bodyOwner(String name){try{return FieldPackage.map(MiniJson.parseObject(Files.readString(draft.getParent().resolve("receipt.json"))).get("body_grouping")).getOrDefault(name,name).toString();}catch(Exception e){return name;}}
    private String[] options(Row row){String k=row.key.toString();return switch(k){case "role"->new String[]{"structure","surface","barrier","apparatus","piece","decoration","reference"};case "collision_strategy"->new String[]{"source","visual","box","sphere","cylinder","mesh","none"};case "mass_mode"->new String[]{"source","override","fallback"};case "inertia_mode"->new String[]{"source","box","override"};case "length_unit"->new String[]{"m","mm","in"};case "floor_strategy"->new String[]{"source","generated"};case "up_axis"->new String[]{"Z","Y"};case "type"->row.path.contains("/joint/")?new String[]{"fixed","revolute","continuous","prismatic"}:null;case "parent"->FieldPackage.map(profile.get("entities")).keySet().toArray(String[]::new);default->{if(k.endsWith("motor")||k.equals("motor")||k.equals("name")&&row.path.contains("/actuators/"))yield hardware();if(row.value instanceof String&&FieldPackage.map(profile.get("entities")).containsKey(row.value))yield FieldPackage.map(profile.get("entities")).keySet().toArray(String[]::new);yield null;}};}
    private String[] hardware(){if(project==null)return null;try{var config=MiniJson.parseObject(Files.readString(project.resolve("sim.config")));return RobotConfigXml.parse(project.resolve(config.get("robotConfig").toString()).toFile()).devices.stream().filter(d->Set.of(RobotConfigXml.DeviceType.MOTOR,RobotConfigXml.DeviceType.SERVO).contains(RobotConfigXml.resolveType(d.tag))).map(d->d.name).toArray(String[]::new);}catch(Exception e){return null;}}
    private final class Properties extends AbstractTableModel {
        private final List<Row> rows=new ArrayList<>();
        void load(Object value,String path){rows.clear();flatten(value,path);fireTableDataChanged();}
        void flatten(Object o,String path){if(rows.size()>1500)return;if(o instanceof Map<?,?> m)for(var e:m.entrySet()){String p=path+"/"+e.getKey();if(e.getValue() instanceof Map || e.getValue() instanceof List)flatten(e.getValue(),p);else if(e.getValue()!=null)rows.add(new Row(o,e.getKey(),e.getValue(),p));}else if(o instanceof List<?> l)for(int i=0;i<l.size();i++){if(l.get(i) instanceof Map || l.get(i) instanceof List)flatten(l.get(i),path+"/"+i);else rows.add(new Row(o,i,l.get(i),path+"/"+i));}}
        public int getRowCount(){return rows.size();}public int getColumnCount(){return 3;}public String getColumnName(int col){return new String[]{"Parameter (units in name)","Effective value","Provenance"}[col];}
        public Object getValueAt(int row,int col){Row r=rows.get(row);return col==0?r.path:col==1?r.value:FieldPackage.map(profile.get("provenance")).getOrDefault(r.path,"source CAD / generated; inspect part assumptions");}
        public boolean isCellEditable(int r,int c){if(c!=1||busy)return false;String p=rows.get(r).path;if(p.startsWith("entities/")&&(p.endsWith("friction")||p.endsWith("restitution")||p.endsWith("material_override"))){String name=unpointer(p.split("/")[1]);if(!bodyOwner(name).equals(name))return false;}return !p.endsWith("/file")&&!p.endsWith("/id")&&(!p.endsWith("/name")||p.contains("/actuators/"))&&!p.endsWith("/version")&&!p.endsWith("/units")&&!p.endsWith("/triangles")&&(!"biobuzz".equals(profile.get("adapter"))||!p.contains("origin_")&&!p.endsWith("length_unit")&&!p.endsWith("up_axis")&&!p.endsWith("floor_strategy"));}
        @SuppressWarnings("unchecked") public void setValueAt(Object value,int row,int col){Row r=rows.get(row);try{Object parsed=r.value instanceof Number?Double.valueOf(value.toString()):r.value instanceof Boolean?value instanceof Boolean?value:Boolean.valueOf(value.toString()):value.toString();if(parsed instanceof Number n&&!Double.isFinite(n.doubleValue()))throw new IllegalArgumentException("Enter a finite number");if(r.path.equals("parameters/length_unit")){ProfileIO.save(draft,profile);work(()->controller.run("units",draft.toString(),parsed.toString()),ModelPreparationEditor.this::open);return;}if(r.parent instanceof Map m)m.put(r.key,parsed);else ((List)r.parent).set((int)r.key,parsed);FieldPackage.map(profile.get("provenance")).put(r.path,"user supplied");if(r.path.startsWith("entities/"))FieldPackage.map(FieldPackage.map(profile.get("entities")).get(unpointer(r.path.split("/")[1]))).put("provenance","user supplied");profile.put("review",new LinkedHashMap<>(Map.of("state","draft")));rows.set(row,new Row(r.parent,r.key,parsed,r.path));fireTableRowsUpdated(row,row);debounce.restart();}catch(Exception e){error(e);}}
    }
}
