package simrunner;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.nio.file.*;
import java.util.*;
import java.util.List;
import simcore.MiniJson;

/** Separate model references and layout; changing a layout never invalidates model review. */
final class SceneEditor {
    private record Choice(Path path,String label){public String toString(){return label;}}
    static void show(ModelEditorController controller,Path project,Component owner){try {
        JDialog w=new JDialog((Frame)SwingUtilities.getWindowAncestor(owner),"FTC Forge — saved scene",false);
        JPanel top=new JPanel(new GridLayout(0,2,8,8));top.setBorder(BorderFactory.createEmptyBorder(12,12,12,12));
        var robots=new ArrayList<Choice>();var fields=new ArrayList<Choice>();robots.add(new Choice(null,"Project robot"));fields.add(new Choice(null,"Generic field"));
        for(Path p:controller.revisions()){var data=MiniJson.parseObject(Files.readString(p));if(!"ready".equals(FieldPackage.map(data.get("review")).get("state")))continue;var choice=new Choice(p,data.get("name")+" | "+data.get("revision_id"));(data.get("model_kind").equals("robot")?robots:fields).add(choice);}
        JComboBox<Choice> robot=new JComboBox<>(robots.toArray(Choice[]::new)),field=new JComboBox<>(fields.toArray(Choice[]::new));
        JComboBox<String> mode=new JComboBox<>(new String[]{"field-only","game-pieces"});
        JComboBox<String> precedence=new JComboBox<>(new String[]{"Saved model settings","Existing project settings"});
        JSpinner[] pose=new JSpinner[4];for(int i=0;i<4;i++)pose[i]=new JSpinner(new SpinnerNumberModel(i==2?.1:0.,-100.,100.,.01));
        for(Object[] row:new Object[][]{{"Robot revision",robot},{"Field revision",field},{"Mode",mode},{"Overlapping physics settings",precedence},{"Robot X (m)",pose[0]},{"Robot Y (m)",pose[1]},{"Robot Z / height (m)",pose[2]},{"Robot yaw (rad)",pose[3]}}){top.add(new JLabel(row[0].toString()));top.add((Component)row[1]);}
        DefaultTableModel pieces=new DefaultTableModel(new String[]{"Piece ID","X (m)","Y (m)","Z / height (m)","Roll (rad)","Pitch (rad)","Yaw (rad)","Enabled","Source piece ID"},0){public boolean isCellEditable(int r,int c){return c>0&&c<8;}public Class<?> getColumnClass(int c){return c==7?Boolean.class:Object.class;}};
        JTable table=new JTable(pieces);table.setRowHeight(24);
        Runnable sourceLayout=()->{pieces.setRowCount(0);Choice choice=(Choice)field.getSelectedItem();if(choice==null||choice.path==null)return;try{var p=new ModelProfile(choice.path,true);List<Map<String,Object>> source;if(p.legacyField())source=new FieldPackage(p.artifact("field")).instances.stream().filter(i->"piece".equals(i.get("owner"))).toList();else source=FieldPackage.maps(FieldPackage.map(p.receipt.get("artifacts")).get("pieces"));for(var inst:source){var xyz=FieldPackage.vector(inst.get("xyz_m"),3);var rpy=FieldPackage.vector(inst.get("rpy_rad"),3);pieces.addRow(new Object[]{inst.get("id"),xyz[0],xyz[1],xyz[2],rpy[0],rpy[1],rpy[2],true,inst.get("id")});}}catch(Exception e){JOptionPane.showMessageDialog(w,e.getMessage());}};
        final int[] previousField={0};final boolean[] selecting={false};
        field.addActionListener(e->{if(selecting[0])return;if(pieces.getRowCount()>0&&JOptionPane.showConfirmDialog(w,"Changing field revision will replace piece placements with the selected model's layout. Continue?","Scene migration",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION){selecting[0]=true;field.setSelectedIndex(previousField[0]);selecting[0]=false;return;}previousField[0]=field.getSelectedIndex();sourceLayout.run();});
        JPanel buttons=new JPanel(new FlowLayout());JLabel status=new JLabel("Meters and model scale remain unchanged. R resets to these saved piece poses.");
        JButton load=new JButton("Open scene…"),save=new JButton("Save scene…"),activate=new JButton("Save and use in project…"),reset=new JButton("Use model piece layout");buttons.add(load);buttons.add(reset);JButton duplicate=new JButton("Duplicate selected piece"),remove=new JButton("Disable selected piece");buttons.add(duplicate);buttons.add(remove);
        duplicate.addActionListener(e->{int r=table.getSelectedRow();if(r<0)return;Object[] row=new Object[9];for(int i=0;i<9;i++)row[i]=pieces.getValueAt(r,i);row[0]="scene-"+java.util.UUID.randomUUID();row[1]=Double.parseDouble(row[1].toString())+.12;row[7]=true;pieces.addRow(row);});remove.addActionListener(e->{int r=table.getSelectedRow();if(r>=0)pieces.setValueAt(false,r,7);});buttons.add(save);buttons.add(activate);activate.setEnabled(project!=null);
        load.addActionListener(e->{var chooser=new JFileChooser();if(chooser.showOpenDialog(w)!=JFileChooser.APPROVE_OPTION)return;try{Path file=chooser.getSelectedFile().toPath().toRealPath();var data=MiniJson.parseObject(Files.readString(file));if(FieldPackage.num(data,"schema_version")!=1)throw new IllegalArgumentException("Unsupported scene version");selecting[0]=true;try{for(var pair:List.of(Map.entry("robot",robot),Map.entry("field",field))){Object ref=data.get(pair.getKey()+"_profile");if(ref==null){pair.getValue().setSelectedIndex(0);continue;}Path path=file.getParent().resolve(ref.toString()).normalize();if(Files.exists(path))path=path.toRealPath();boolean found=false;for(int i=0;i<pair.getValue().getItemCount();i++)if(pair.getValue().getItemAt(i).path!=null&&path.equals(pair.getValue().getItemAt(i).path.toRealPath())){pair.getValue().setSelectedIndex(i);found=true;break;}if(!found){pair.getValue().setSelectedIndex(0);JOptionPane.showMessageDialog(w,"The saved "+pair.getKey()+" revision is unavailable. Select its replacement from the library.");}}}finally{selecting[0]=false;previousField[0]=field.getSelectedIndex();}sourceLayout.run();mode.setSelectedItem(data.get("mode"));var xyz=FieldPackage.vector(data.get("robot_start_xyz_m"),3);for(int i=0;i<3;i++)pose[i].setValue(xyz[i]);pose[3].setValue(FieldPackage.num(data,"robot_start_yaw_rad"));var saved=FieldPackage.map(data.get("pieces"));Set<String> matched=new HashSet<>();for(int r=0;r<pieces.getRowCount();r++){String id=pieces.getValueAt(r,0).toString();if(saved.containsKey(id)){var m=FieldPackage.map(saved.get(id));var a=FieldPackage.vector(m.get("xyz_m"),3);var b=FieldPackage.vector(m.get("rpy_rad"),3);for(int i=0;i<3;i++){pieces.setValueAt(a[i],r,i+1);pieces.setValueAt(b[i],r,i+4);}pieces.setValueAt(m.getOrDefault("enabled",true),r,7);pieces.setValueAt(m.getOrDefault("source_id",id),r,8);matched.add(id);}}for(String id:saved.keySet())if(!matched.contains(id)&&FieldPackage.map(saved.get(id)).containsKey("source_id")){var m=FieldPackage.map(saved.get(id));String source=m.get("source_id").toString();boolean found=false;for(int r=0;r<pieces.getRowCount();r++)if(source.equals(pieces.getValueAt(r,8)))found=true;if(found){var a=FieldPackage.vector(m.get("xyz_m"),3);var b=FieldPackage.vector(m.get("rpy_rad"),3);pieces.addRow(new Object[]{id,a[0],a[1],a[2],b[0],b[1],b[2],m.getOrDefault("enabled",true),source});matched.add(id);}}
                for(String id:saved.keySet())if(!matched.contains(id)){Object selected=JOptionPane.showInputDialog(w,"Saved piece "+id+" is missing. Choose a new piece to receive its placement, or retain the source layout.","Migrate piece placement",JOptionPane.QUESTION_MESSAGE,null,java.util.stream.Stream.concat(java.util.stream.Stream.of("Keep source layout"),java.util.stream.IntStream.range(0,pieces.getRowCount()).mapToObj(r->pieces.getValueAt(r,0).toString())).toArray(),"Keep source layout");if(selected!=null&&!selected.equals("Keep source layout"))for(int r=0;r<pieces.getRowCount();r++)if(selected.equals(pieces.getValueAt(r,0))){var m=FieldPackage.map(saved.get(id));var a=FieldPackage.vector(m.get("xyz_m"),3);var b=FieldPackage.vector(m.get("rpy_rad"),3);for(int i=0;i<3;i++){pieces.setValueAt(a[i],r,i+1);pieces.setValueAt(b[i],r,i+4);}}}status.setText("Loaded layout; verify selected model revisions before saving.");}catch(Exception error){JOptionPane.showMessageDialog(w,error.getMessage());}});
        reset.addActionListener(e->sourceLayout.run());
        java.util.function.Consumer<Boolean> write=use->{if(table.isEditing())table.getCellEditor().stopCellEditing();var chooser=new JFileChooser();if(chooser.showSaveDialog(w)!=JFileChooser.APPROVE_OPTION)return;try{Path out=chooser.getSelectedFile().toPath().toAbsolutePath();Files.createDirectories(out.getParent());out=out.getParent().toRealPath().resolve(out.getFileName());Map<String,Object> data=new LinkedHashMap<>();data.put("schema_version",1);for(var pair:List.of(Map.entry("robot",(Choice)robot.getSelectedItem()),Map.entry("field",(Choice)field.getSelectedItem()))){Path file=pair.getValue().path;if(file!=null)file=file.toRealPath();data.put(pair.getKey()+"_profile",file==null?null:out.getParent().relativize(file).toString());if(file!=null){var p=new ModelProfile(file,true);data.put(pair.getKey()+"_identity",Map.of("profile_id",p.data.get("profile_id"),"revision_id",p.data.get("revision_id")));}}data.put("mode",mode.getSelectedItem());data.put("robot_start_xyz_m",List.of(pose[0].getValue(),pose[1].getValue(),pose[2].getValue()));data.put("robot_start_yaw_rad",pose[3].getValue());var placements=new LinkedHashMap<String,Object>();if(mode.getSelectedItem().equals("game-pieces"))for(int r=0;r<pieces.getRowCount();r++){var xyz=new ArrayList<Double>();var rpy=new ArrayList<Double>();for(int c=1;c<=3;c++){xyz.add(Double.parseDouble(pieces.getValueAt(r,c).toString()));rpy.add(Double.parseDouble(pieces.getValueAt(r,c+3).toString()));}placements.put(pieces.getValueAt(r,0).toString(),Map.of("xyz_m",xyz,"rpy_rad",rpy,"enabled",pieces.getValueAt(r,7),"source_id",pieces.getValueAt(r,8)));}data.put("pieces",placements);ProfileIO.save(out,data);if(use){Path cfg=project.resolve("sim.config");var original=MiniJson.parseObject(Files.readString(cfg));var changed=new LinkedHashMap<>(original);changed.put("scene_profile",out.toString());changed.put("model_settings",precedence.getSelectedIndex()==0?"profile":"project");ProfileIO.save(cfg,changed);try{SimConfig.load(project);}catch(Exception failure){ProfileIO.save(cfg,original);throw failure;}}status.setText("Saved scene: "+out);}catch(Exception error){JOptionPane.showMessageDialog(w,error.getMessage(),"Scene needs attention",JOptionPane.ERROR_MESSAGE);}};
        save.addActionListener(e->write.accept(false));activate.addActionListener(e->write.accept(true));
        w.add(top,BorderLayout.NORTH);w.add(new JScrollPane(table));JPanel bottom=new JPanel(new GridLayout(0,1));bottom.add(buttons);bottom.add(status);w.add(bottom,BorderLayout.SOUTH);w.setSize(1000,760);w.setLocationRelativeTo(owner);w.setVisible(true);
    }catch(Exception e){JOptionPane.showMessageDialog(owner,e.getMessage(),"Cannot open scenes",JOptionPane.ERROR_MESSAGE);}}
}
