package simrunner;

import physics.TireFriction;
import physics.calibration.TireSlipCalibrator.*;
import java.awt.*;
import java.nio.file.*;
import java.util.*;
import java.util.List;
import javax.swing.*;

/** Guided SI CSV experiment import, identification preview and explicit measured application. */
final class TireSlipCalibrationGuide {
    record Snapshot(String group,List<String> joints,TireFriction.Spec spec,Map<String,Object> evidence) {}
    static Snapshot read(GuidedSetupController c,String group)throws Exception {
        var choices=c.tireClassChoices();if(!choices.containsKey(group))throw new IllegalArgumentException("Choose a configured tire class");var tires=FieldPackage.map(FieldPackage.map(c.session.profile("robot").get("runtime")).get("tires"));var cfg=TireDriveConfig.parse(tires,false);var values=FieldPackage.map(tires.get(group));return new Snapshot(group,choices.get(group),group.equals("traction")?cfg.traction():cfg.omni(),values.containsKey("measurement")?FieldPackage.map(values.get("measurement")):Map.of());
    }
    private static final class Panel extends JPanel implements Scrollable {
        public Dimension getPreferredScrollableViewportSize(){return new Dimension(950,640);}public int getScrollableUnitIncrement(Rectangle r,int o,int d){return 24;}public int getScrollableBlockIncrement(Rectangle r,int o,int d){return r.height-24;}public boolean getScrollableTracksViewportWidth(){return true;}public boolean getScrollableTracksViewportHeight(){return false;}
    }
    private final JPanel panel=new Panel();private final Snapshot snapshot;
    private final JTextField surface=new JTextField(32),hubSource=new JTextField(32),forceSource=new JTextField(32);
    private final Map<String,JSpinner> bounds=new LinkedHashMap<>(),criteria=new LinkedHashMap<>();
    private final JCheckBox physical=new JCheckBox("I confirm these are independent physical steady trials with directly measured force and hub speed.");
    private final JLabel status=new JLabel("No readings loaded. Import your physical SI CSV; examples are not prefilled.");
    private List<TireSlipMeasurement.Row> readings=List.of();
    private TireSlipCalibrationGuide(Snapshot s) {
        snapshot=s;panel.setLayout(new BoxLayout(panel,BoxLayout.Y_AXIS));panel.setBorder(BorderFactory.createEmptyBorder(8,8,8,8));
        section("1. Measure steady longitudinal slip", "Class: "+s.group()+". Current wheel joints: "+String.join(", ",s.joints())+". Use one representative tread/surface/direction at a time. Measure wheel surface speed and independent hub ground speed along the wheel's forward axis; slip is their difference. Measure normal load and longitudinal tire force directly. Keep lateral motion near zero and speed/load steady. Motor current or encoder-derived hub speed cannot supply independent force/traction evidence. The fit applies to every wheel in this class; test variation between wheels before reusing it.");
        panel.add(row("Reference surface / condition",surface));panel.add(row("Independent hub-speed measurement source",hubSource));panel.add(row("Direct longitudinal-force measurement source",forceSource));
        section("2. Import independent physical trials", "SI CSV columns: joint, trial, set, wheel_surface_mps, hub_speed_mps, normal_load_n, longitudinal_force_n. Reserve whole trials for validation before fitting. Use at least 12 fitting and 6 validation experiments, with both slip signs, different loads, low slip, transition and high-slip plateau conditions. Repeated steady samples share one ID and count once. Each wheel experiment needs a distinct trial ID. Positive force has the sign of wheel surface speed minus hub speed. Normal load is positive N; speeds m/s; force signed N.");
        var actions=new JPanel(new GridLayout(0,2,6,6));actions.setAlignmentX(Component.LEFT_ALIGNMENT);button(actions,"Import tire readings CSV…",this::importCsv);button(actions,"Save blank tire CSV template…",this::template);button(actions,"Export loaded SI readings…",this::exportCsv);actions.setMaximumSize(new Dimension(Integer.MAX_VALUE,actions.getPreferredSize().height));panel.add(actions);panel.add(status);
        section("3. Review search bounds and quality criteria", "These defaults are assumptions and are saved with the report. Search fits static_mu, sliding_mu, stiffness (N per m/s) and transition speed (m/s), with sliding ≤ static. Boundary fits, weak sensitivities and correlated parameters block application. Relaxing quality thresholds does not improve physical accuracy. Lateral scale, shaft inertia and geometry keep their saved values.");
        var b=TireSlipMeasurement.bounds(Bounds.defaults());for(String pair:List.of("static","sliding","stiffness","transition")){JSpinner lo=spinner(b.get("min_"+pair)),hi=spinner(b.get("max_"+pair));bounds.put("min_"+pair,lo);bounds.put("max_"+pair,hi);panel.add(row(pair+" lower / upper",lo,hi));}
        var defaults=TireSlipMeasurement.criteria(Criteria.defaults());for(String key:List.of("min_fit_trials","min_validation_trials","min_load_variation","max_relative_rmse","max_trial_error","max_slip_spread","max_load_spread","min_sensitivity","min_information_eigenvalue")){var input=spinner(defaults.get(key));criteria.put(key,input);panel.add(row(key.replace('_',' '),input));}
        panel.add(physical);panel.add(text("Native material grip is an additional force cap. Use the same reference surface and a wheel/surface material budget sufficient for this curve; this workflow does not change wheel friction or field settings. The fit is a steady longitudinal law, not dynamic acceleration, lateral friction, rollers or inertia calibration. Applying it saves a draft requiring collision and motion review."));
        if(!s.evidence().isEmpty())try{var e=s.evidence();var context=TireSlipMeasurement.context(e);surface.setText(context.surface());hubSource.setText(context.hubSource());forceSource.setText(context.forceSource());readings=TireSlipMeasurement.readings(e);loadSpinners(bounds,FieldPackage.map(e.get("bounds")));loadSpinners(criteria,FieldPackage.map(e.get("criteria")));try{TireSlipMeasurement.check(e,s.group(),s.spec());status.setText("Loaded "+readings.size()+" saved readings. Original joint labels remain historical after CAD migration. Review applicability before refitting.");}catch(Exception ex){status.setText("Saved tire evidence needs refitting: "+ex.getMessage());}}catch(Exception ex){status.setText("Cannot reload evidence: "+ex.getMessage()+". Import new readings or discard saved evidence.");}
        surface.getAccessibleContext().setAccessibleName("Tire reference surface");hubSource.getAccessibleContext().setAccessibleName("Independent tire hub speed source");forceSource.getAccessibleContext().setAccessibleName("Direct tire force source");
    }
    private static JSpinner spinner(Object value){var s=new JSpinner(new SpinnerNumberModel(((Number)value).doubleValue(),.000001,100000.,.01));((JSpinner.DefaultEditor)s.getEditor()).getTextField().setColumns(8);return s;}
    private static void loadSpinners(Map<String,JSpinner> fields,Map<String,Object> data){for(var entry:fields.entrySet())entry.getValue().setValue(FieldPackage.num(data,entry.getKey()));}
    private Map<String,Object> values(Map<String,JSpinner> fields)throws Exception{var m=new LinkedHashMap<String,Object>();for(var e:fields.entrySet()){e.getValue().commitEdit();m.put(e.getKey(),e.getValue().getValue());}return m;}
    private void importCsv(){var c=new JFileChooser();if(c.showOpenDialog(panel)!=JFileChooser.APPROVE_OPTION)return;try{readings=TireSlipMeasurement.readCsv(c.getSelectedFile().toPath(),new HashSet<>(snapshot.joints()));status.setText("Loaded "+readings.size()+" SI readings. Review context and preview fit.");}catch(Exception e){failure(e);}}
    private Path destination(String name){var c=new JFileChooser();c.setSelectedFile(new java.io.File(name));if(c.showSaveDialog(panel)!=JFileChooser.APPROVE_OPTION)return null;Path p=c.getSelectedFile().toPath();if(Files.exists(p)&&JOptionPane.showConfirmDialog(panel,"Replace "+p.getFileName()+"?","Export tire readings",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return null;return p;}
    private void template(){Object selected=JOptionPane.showInputDialog(panel,"Wheel for the blank SI template","Recorded wheel",JOptionPane.QUESTION_MESSAGE,null,snapshot.joints().toArray(),snapshot.joints().get(0));if(selected==null)return;Path p=destination("tire-slip-template.csv");if(p==null)return;try{TireSlipMeasurement.template(p,selected.toString());status.setText("Blank template saved. Fill actual readings; add more independent conditions as needed.");}catch(Exception e){failure(e);}}
    private void exportCsv(){if(readings.isEmpty()){failure(new IllegalArgumentException("Import physical readings first"));return;}Path p=destination("tire-slip-readings.csv");if(p==null)return;try{Files.writeString(p,TireSlipMeasurement.csv(readings));status.setText("Loaded SI readings exported.");}catch(Exception e){failure(e);}}
    private void failure(Exception e){JOptionPane.showMessageDialog(panel,e.getMessage(),"Check tire measurements",JOptionPane.ERROR_MESSAGE);}
    private void section(String title,String body){var l=new JLabel(title);l.setFont(l.getFont().deriveFont(Font.BOLD,15));l.setBorder(BorderFactory.createEmptyBorder(10,0,6,0));l.setAlignmentX(Component.LEFT_ALIGNMENT);panel.add(l);panel.add(text(body));}
    private static JTextArea text(String value){var t=new JTextArea(value);t.setEditable(false);t.setOpaque(false);t.setLineWrap(true);t.setWrapStyleWord(true);t.setColumns(85);t.setRows((value.length()+104)/105);t.setAlignmentX(Component.LEFT_ALIGNMENT);t.setMaximumSize(new Dimension(Integer.MAX_VALUE,t.getPreferredSize().height));return t;}
    private static JPanel row(String label,Component...fields){var p=new JPanel(new FlowLayout(FlowLayout.LEFT));p.setAlignmentX(Component.LEFT_ALIGNMENT);p.add(new JLabel(label));for(var f:fields)p.add(f);p.setMaximumSize(new Dimension(Integer.MAX_VALUE,p.getPreferredSize().height));return p;}
    private static void button(JPanel p,String label,Runnable r){var b=new JButton(label);b.addActionListener(e->r.run());p.add(b);}
    private static String format(double x){return String.format(Locale.ROOT,"%.5g",x);}
    static String summary(Result r){return (r.accepted()?"Quality and identification checks passed.":"Quality/identification checks failed; settings cannot be applied.")+"\nstatic_mu "+format(r.spec().staticMu())+" · sliding_mu "+format(r.spec().slidingMu())+"\nstiffness "+format(r.spec().stiffnessNPerMps())+" N per m/s · transition "+format(r.spec().transitionMps())+" m/s\nIndependent trials: "+r.fitTrials()+" fit / "+r.validationTrials()+" validation\nForce RMSE: "+format(r.fitRmseN())+" N fit / "+format(r.validationRmseN())+" N validation\nRelative RMSE: "+format(r.fitRelativeRmse())+" fit / "+format(r.validationRelativeRmse())+" validation\nWorst trial relative error: "+format(r.worstTrialError())+"\nMinimum log-parameter sensitivity: "+format(r.minSensitivity())+" · information eigenvalue: "+format(r.informationEigenvalue())+"\n"+String.join("\n",r.issues())+"\n\nPassing supplied trials does not prove hardware accuracy. Use consistent surface/material settings; review collisions and motion after applying.";}
    static Map<String,Object> show(Component parent,Snapshot snapshot) {
        var guide=new TireSlipCalibrationGuide(snapshot);var scroll=new JScrollPane(guide.panel);scroll.setPreferredSize(new Dimension(950,640));scroll.getVerticalScrollBar().setUnitIncrement(24);
        while(true){SwingUtilities.invokeLater(()->{guide.surface.requestFocusInWindow();scroll.getVerticalScrollBar().setValue(0);});int answer=JOptionPane.showOptionDialog(parent,scroll,"Measure tire slip — "+snapshot.group(),JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,new String[]{"Fit and preview","Cancel"},"Fit and preview");if(answer!=0)return null;
            try{var context=new TireSlipMeasurement.Context(snapshot.group(),guide.surface.getText().strip(),guide.hubSource.getText().strip(),guide.forceSource.getText().strip());var bounds=TireSlipMeasurement.readBounds(guide.values(guide.bounds));var criteria=TireSlipMeasurement.readCriteria(guide.values(guide.criteria));var r=TireSlipMeasurement.fit(guide.readings,snapshot.spec().lateralScale(),bounds,criteria);boolean apply=r.accepted()&&guide.physical.isSelected();String message=summary(r)+(r.accepted()&&!apply?"\nConfirm the independent physical source before applying.":"");String[] choices=apply?new String[]{"Apply measured tire settings","Back to readings","Cancel"}:new String[]{"Back to readings","Cancel"};var preview=new JScrollPane(text(message));preview.setPreferredSize(new Dimension(950,430));int choice=JOptionPane.showOptionDialog(parent,preview,"Tire slip fit preview",JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,null,choices,choices[0]);if(apply&&choice==0)return TireSlipMeasurement.evidence(context,guide.readings,snapshot.spec().lateralScale(),bounds,criteria);if(choice<0||choice==choices.length-1)return null;}catch(Exception e){guide.failure(e);}
        }
    }
}
