package physics.calibration;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
import physics.calibration.GripCalibrator.*;

class GripCalibratorTest {
    List<Reading> sample(){return new ArrayList<>(List.of(new Reading("fit1","fit",10,4.5),new Reading("fit2","fit",20,9),new Reading("fit3","fit",30,13.5),new Reading("check1","validate",15,6.75),new Reading("check2","validate",25,11.25)));}
    @Test void recoversKnownGripAndPredictsIndependentTrials(){var r=GripCalibrator.fit(sample(),.6,Criteria.defaults());assertTrue(r.accepted());assertEquals(.45,r.effectiveMu(),1e-12);assertEquals(.75,r.wheelCoefficient(),1e-12);assertEquals(0,r.validationRmseN(),1e-12);assertEquals(3,r.fitTrials());assertEquals(2,r.validationTrials());}
    @Test void heldOutDisagreementRejectsWithoutChangingTheFit(){var data=sample();data.set(3,new Reading("check1","validate",15,3));var r=GripCalibrator.fit(data,.6,Criteria.defaults());assertEquals(.75,r.wheelCoefficient(),1e-12);assertFalse(r.accepted());assertTrue(r.issues().stream().anyMatch(s->s.contains("Independent validation")));}
    @Test void noisyButRepeatableTrialsPassAndReportNonzeroErrors(){var data=sample();data.set(0,new Reading("fit1","fit",10,4.6));data.set(3,new Reading("check1","validate",15,6.8));var r=GripCalibrator.fit(data,.6,Criteria.defaults());assertTrue(r.accepted(),r.toString());assertTrue(r.fitRmseN()>0);assertTrue(r.validationRmseN()>0);assertEquals(.75,r.wheelCoefficient(),.002);}
    @Test void repeatsDoNotCountAsIndependentTrialsOrOverweightOneRun(){var data=sample();data.set(0,new Reading("fit1","fit",10,5));var once=GripCalibrator.fit(data,.6,Criteria.defaults());for(int i=0;i<100;i++)data.add(data.get(0));var repeated=GripCalibrator.fit(data,.6,Criteria.defaults());assertEquals(once.wheelCoefficient(),repeated.wheelCoefficient(),1e-12);assertEquals(once.fitRelativeRmse(),repeated.fitRelativeRmse(),1e-12);assertEquals(3,repeated.fitTrials());var tooFew=List.of(new Reading("onlyFit","fit",10,4.5),new Reading("onlyFit","fit",20,9),new Reading("onlyFit","fit",30,13.5),new Reading("v1","validate",15,6.75),new Reading("v2","validate",25,11.25));assertThrows(IllegalArgumentException.class,()->GripCalibrator.fit(tooFew,.6,Criteria.defaults()));}
    @Test void wholeTrialsCannotLeakAcrossSets(){var data=sample();data.add(new Reading("fit1","validate",15,6.75));assertTrue(assertThrows(IllegalArgumentException.class,()->GripCalibrator.fit(data,.6,Criteria.defaults())).getMessage().contains("both sets"));}
    @Test void rejectsUninformativeLoadsZeroSignalAndUnsupportedCoefficient(){var data=sample();data.replaceAll(r->new Reading(r.trial(),r.set(),20,9));assertFalse(GripCalibrator.fit(data,.6,Criteria.defaults()).accepted());data.replaceAll(r->new Reading(r.trial(),r.set(),20,0));assertFalse(GripCalibrator.fit(data,.6,Criteria.defaults()).accepted());var r=GripCalibrator.fit(sample(),.1,Criteria.defaults());assertFalse(r.accepted());assertEquals(4.5,r.wheelCoefficient(),1e-12);assertTrue(r.issues().stream().anyMatch(s->s.contains("not clamped")));}
    @Test void singleBadTrialCannotHideAmongManyGoodOnes(){var data=sample();for(int i=0;i<100;i++)data.add(new Reading("good"+i,"validate",20,9));data.add(new Reading("bad","validate",20,1));var r=GripCalibrator.fit(data,.6,Criteria.defaults());assertTrue(r.validationRelativeRmse()<.15);assertFalse(r.accepted());assertTrue(r.issues().stream().anyMatch(s->s.contains("per-trial")));}
    @Test void criteriaAndInvalidReadingsHaveFiniteBounds(){assertThrows(IllegalArgumentException.class,()->new Reading("x","fit",0,1));assertThrows(IllegalArgumentException.class,()->new Reading("x","fit",20,Double.NaN));assertThrows(IllegalArgumentException.class,()->new Reading("x",null,20,1));assertThrows(IllegalArgumentException.class,()->new Criteria(2,2,.2,.15,.25));assertThrows(IllegalArgumentException.class,()->new Criteria(3,2,.2,Double.NaN,.25));for(double surface:new double[]{0,-1,Double.NaN,3})assertThrows(IllegalArgumentException.class,()->GripCalibrator.fit(sample(),surface,Criteria.defaults()));}
}
