package physics.calibration;
import physics.TireFriction;
import physics.calibration.TireSlipCalibrator.*;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
class TireSlipCalibratorTest {
    static final TireFriction.Spec TRUE=new TireFriction.Spec(.9,.6,1,100,.15);
    List<Reading> data(){var rows=new ArrayList<Reading>();for(String set:List.of("fit","validate"))for(double load:set.equals("fit")?new double[]{2,5,20}:new double[]{3,8,15})for(double v:set.equals("fit")?new double[]{.003,.012,.035,.075,.12,.22,.45,.9}:new double[]{.005,.02,.055,.1,.17,.32,.7})for(int sign:new int[]{-1,1}){double slip=sign*v;rows.add(new Reading(set+rows.size(),set,.3+slip,.3,load,TireFriction.steadyLongitudinal(TRUE,slip,load)));}return rows;}
    @Test void recoversFourParametersAndPredictsReservedTrials(){var r=TireSlipCalibrator.fit(data(),1,Bounds.defaults(),Criteria.defaults());assertTrue(r.accepted(),r.toString());assertEquals(.9,r.spec().staticMu(),.003);assertEquals(.6,r.spec().slidingMu(),.003);assertEquals(100,r.spec().stiffnessNPerMps(),.3);assertEquals(.15,r.spec().transitionMps(),.001);assertTrue(r.validationRelativeRmse()<.001);assertTrue(r.informationEigenvalue()>.001);}
    @Test void badHeldOutForceDoesNotChangeFit(){var good=TireSlipCalibrator.fit(data(),1,Bounds.defaults(),Criteria.defaults());var rows=data();rows.replaceAll(r->r.set().equals("validate")?new Reading(r.trial(),r.set(),r.wheelMps(),r.hubMps(),r.normalN(),r.forceN()*.5):r);var bad=TireSlipCalibrator.fit(rows,1,Bounds.defaults(),Criteria.defaults());assertEquals(good.spec(),bad.spec());assertFalse(bad.accepted());assertTrue(bad.issues().stream().anyMatch(s->s.contains("validation")));}
    @Test void unequalRepeatsDoNotReweightExperiments(){var rows=data();var once=TireSlipCalibrator.fit(rows,1,Bounds.defaults(),Criteria.defaults());for(int i=0;i<20;i++)rows.add(rows.get(0));var repeated=TireSlipCalibrator.fit(rows,1,Bounds.defaults(),Criteria.defaults());assertEquals(once.spec().staticMu(),repeated.spec().staticMu(),1e-6);assertEquals(once.fitTrials(),repeated.fitTrials());}
    @Test void lowSlipOnlyCannotIdentifyFrictionOrTransition(){var rows=data();rows.replaceAll(r->{double slip=Math.copySign(.001,r.slip());return new Reading(r.trial(),r.set(),.3+slip,.3,r.normalN(),100*slip);});var r=TireSlipCalibrator.fit(rows,1,Bounds.defaults(),Criteria.defaults());assertFalse(r.accepted());assertTrue(r.issues().stream().anyMatch(s->s.contains("sensitivity")||s.contains("unidentifiable")));}
    @Test void plateauOnlyCannotIdentifyStiffnessAndTransition(){var rows=data();rows.replaceAll(r->{double slip=Math.copySign(2,r.slip());return new Reading(r.trial(),r.set(),.3+slip,.3,r.normalN(),.6*r.normalN()*Math.signum(slip));});assertFalse(TireSlipCalibrator.fit(rows,1,Bounds.defaults(),Criteria.defaults()).accepted());}
    @Test void noisyDataPassesButUnsteadyTrialsAndBoundFitsDoNot(){var rows=data();for(int i=0;i<rows.size();i++){var r=rows.get(i);rows.set(i,new Reading(r.trial(),r.set(),r.wheelMps(),r.hubMps(),r.normalN(),r.forceN()*(1+.01*Math.sin(i))));}assertTrue(TireSlipCalibrator.fit(rows,1,Bounds.defaults(),Criteria.defaults()).accepted());var first=rows.get(0);rows.add(new Reading(first.trial(),first.set(),first.wheelMps()-.05,first.hubMps(),first.normalN(),-0.1));assertFalse(TireSlipCalibrator.fit(rows,1,Bounds.defaults(),Criteria.defaults()).accepted());assertFalse(TireSlipCalibrator.fit(data(),1,new Bounds(.1,2,.05,2,1,80,.01,1),Criteria.defaults()).accepted());}
    @Test void leakageCountsSignsAndBoundsAreRejected(){var rows=data();var r=rows.get(0);rows.add(new Reading(r.trial(),"validate",r.wheelMps(),r.hubMps(),r.normalN(),r.forceN()));assertThrows(IllegalArgumentException.class,()->TireSlipCalibrator.fit(rows,1,Bounds.defaults(),Criteria.defaults()));assertThrows(IllegalArgumentException.class,()->new Reading("bad","fit",1,0,10,-1));assertThrows(IllegalArgumentException.class,()->new Reading("bad","fit",Double.NaN,0,10,1));assertThrows(IllegalArgumentException.class,()->new Bounds(.1,2,2,3,1,1000,.01,1));assertThrows(IllegalArgumentException.class,()->TireSlipCalibrator.fit(data().subList(0,5),1,Bounds.defaults(),Criteria.defaults()));}
    @Test void steadyEnvelopeMatchesRuntimeAsIntegrationIntervalShrinks(){for(double slip:new double[]{-.8,-.1,-.003,0,.003,.1,.8})assertEquals(TireFriction.steadyLongitudinal(TRUE,slip,5),TireFriction.solve(TRUE,slip,0,5,1e-10,1,1).longitudinalN(),1e-6);}
}
